import {Lifecycle} from '../knowledge/Lifecycle';
import {SupportViewer} from '../settings/Support';
import {useEffect,useState,type FormEvent} from 'react';import {api,ApiError} from '@/api/api';
type Provider={id:string,name:string,adapter:string,enabled:boolean};type Model={id:string,provider_id:string,name:string,capabilities:string[],enabled:boolean};type Grant={id:string,workspace_id:string,model_id:string,capability:string,active:boolean};type Registry={providers:Provider[],models:Model[],grants:Grant[]};
function Text({name,label,pattern}:{name:string,label:string,pattern?:string}){return <label className="field">{label}<input name={name} required maxLength={name==='reason'?500:100} minLength={name==='reason'?5:1} pattern={pattern}/></label>;}
export function Platform(){
 const[agentMessage,setAgentMessage]=useState(''),[agentSessionId,setAgentSessionId]=useState<string|undefined>(),[agentContext,setAgentContext]=useState(''),[agentReply,setAgentReply]=useState(''),[agentHistory,setAgentHistory]=useState<any[]>([]),[data,setData]=useState<Registry|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[denied,setDenied]=useState(false),[modelId,setModelId]=useState('');
 async function load(){try{setData(await api('/platform/registry'));setDenied(false);setError('');return true;}catch(e){setError((e as Error).message);if(e instanceof ApiError&&['PLATFORM_FORBIDDEN','UNAUTHENTICATED'].includes(e.code)){setDenied(true);setData(null);}return false;}}
 useEffect(()=>{void load();},[]);
 async function submit(e:FormEvent<HTMLFormElement>,endpoint:string,convert:(f:FormData)=>unknown,method='POST'){e.preventDefault();const form=e.currentTarget;setBusy(true);setError('');setMessage('');try{await api(endpoint,method,convert(new FormData(form)));form.reset();const refreshed=await load();setMessage(refreshed?'Đã lưu cấu hình và đọc lại từ hệ thống.':'Đã lưu; chưa đọc lại được dữ liệu. Hãy bấm Làm mới.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const chatModels=data?.models.filter(m=>m.enabled&&m.capabilities.includes('chat')&&data.providers.some(p=>p.id===m.provider_id&&p.enabled))??[];
 return <div className="platform"><header><img src="/gotek-logo.png" alt="gotek" style={{width:100}}/><strong>Platform Admin</strong><a href="/settings/general">Về workspace</a></header><main className="content"><h1>Provider và model</h1><section className="panel"><h2>AI Agent Platform</h2><p className="muted">Chỉ Platform Admin được dùng; nội dung không thuộc workspace CRM.</p><form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);setError('');try{const m=await api('/platform/agent/chat','POST',{requestId:crypto.randomUUID(),sessionId:agentSessionId,message:f.get('message'),modelId:f.get('modelId'),context:agentContext.trim()?[{source:'Platform Admin input',title:'Context cung cấp',content:agentContext.trim()}]:[]});setAgentReply(m.message?.content||m.error||m.state);setAgentSessionId(m.sessionId);if(m.sessionId){try{setAgentHistory(await api(`/platform/agent/sessions/${m.sessionId}/messages`));}catch{setAgentHistory([]);}}setAgentMessage('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><label className="field">Model<select name="modelId" required>{chatModels.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><label className="field">Yêu cầu phân tích context<textarea name="message" value={agentMessage} onChange={e=>setAgentMessage(e.target.value)} required maxLength={20000}/> </label><label className="field">Context bổ sung<textarea name="context" value={agentContext} onChange={e=>setAgentContext(e.target.value)} maxLength={8000} placeholder="Dán context đã được phép sử dụng…"/></label><button className="primary" disabled={busy||!chatModels.length}>Gửi cho AI Agent</button></form><button type="button" disabled={busy||!agentSessionId} onClick={()=>{setAgentSessionId(undefined);setAgentHistory([]);setAgentReply('');}}>Phiên mới</button>{agentReply&&<div role="status" className="notice">{agentReply}</div>}{agentHistory.length>0&&<div className="table-wrap"><h3>Lịch sử phiên hiện tại</h3><ol>{agentHistory.map((item:any)=><li key={item.id}><strong>{item.role==='user'?'Bạn':'AI Agent'}</strong>: {item.content} <small>({item.status})</small></li>)}</ol></div>}</section><p className="muted">Quản lý cấu hình AI cấp nền tảng. Quyền này không cho phép đọc nội dung hội thoại của workspace.</p>{error&&<div role="alert" className="notice error">{error}</div>}{message&&<div role="status" className="notice">{message}</div>}<button disabled={busy} onClick={load}>Làm mới</button>{denied?<p>Cần quyền Platform Admin để truy cập. <a href="/app/login">Đăng nhập</a></p>:!data?<p role="status">Đang tải danh mục…</p>:<>
 <section className="panel"><h2>Thêm provider</h2><form onSubmit={e=>submit(e,'/platform/providers',f=>Object.fromEntries(f))}><fieldset disabled={busy}><Text name="name" label="Tên provider"/><label className="field">Adapter<select name="adapter"><option value="openai">OpenAI</option><option value="chatgpt">ChatGPT</option><option value="anthropic">Anthropic</option><option value="gemini">Gemini</option><option value="claude_code">Claude Code</option><option value="custom_llm">LLM riêng</option><option value="local">Local</option></select></label><Text name="secretRef" label="Tên biến môi trường chứa khóa" pattern="[A-Z][A-Z0-9_]{2,79}"/><Text name="baseUrl" label="Base URL tùy chọn (LLM riêng)"/><p className="muted">Chỉ nhập tên tham chiếu. Khóa được cấu hình trên server.</p><Text name="reason" label="Lý do"/><button className="primary">{busy?'Đang lưu…':'Thêm provider'}</button></fieldset></form></section>
 <h2>Danh mục provider</h2>{!data.providers.length?<p className="empty">Chưa có provider.</p>:data.providers.map(p=><section className="panel" key={p.id}><h3>{p.name} · {p.adapter}</h3><p>{p.enabled?'Đã bật':'Đang tắt'}</p><button disabled={busy} onClick={async()=>{setBusy(true);setError('');try{const r=await api(`/platform/providers/${p.id}/test`,'POST',{});setMessage(r.status==='confirmed'?'Kiểm tra provider thành công.':r.status==='not_configured'?'Provider chưa có engine suy luận.':`Provider trả lỗi: ${r.error||r.status}`);await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>Kiểm tra kết nối</button><form onSubmit={e=>submit(e,`/platform/providers/${p.id}/state`,f=>({enabled:!p.enabled,reason:f.get('reason')}),'PATCH')}><fieldset disabled={busy}><Text name="reason" label="Lý do thay đổi trạng thái"/><button>{p.enabled?'Tắt provider':'Bật provider'}</button></fieldset></form></section>)}
 <section className="panel"><h2>Thêm model</h2><form onSubmit={e=>submit(e,'/platform/models',f=>({providerId:f.get('providerId'),name:f.get('name'),capabilities:f.getAll('capabilities'),reason:f.get('reason')}))}><fieldset disabled={busy||!data.providers.length}><label className="field">Provider<select name="providerId" required>{data.providers.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><Text name="name" label="Tên model tại provider"/><fieldset><legend>Khả năng hỗ trợ</legend>{['chat','embedding','vision'].map(c=><label key={c} style={{marginRight:16}}><input type="checkbox" name="capabilities" value={c}/>{c}</label>)}</fieldset><Text name="reason" label="Lý do"/><button className="primary">Thêm model</button></fieldset></form></section>
 <h2>Danh mục model</h2>{!data.models.length?<p>Chưa có model.</p>:<div className="table-wrap"><table><thead><tr><th>Model</th><th>Provider</th><th>Khả năng</th><th>Trạng thái</th><th>Điều khiển</th></tr></thead><tbody>{data.models.map(m=><tr key={m.id}><td>{m.name}</td><td>{data.providers.find(p=>p.id===m.provider_id)?.name}</td><td>{m.capabilities.join(', ')}</td><td>{m.enabled?'Hoạt động':'Tắt'}</td><td><form onSubmit={e=>submit(e,`/platform/models/${m.id}/state`,f=>({enabled:!m.enabled,reason:f.get('reason')}),'PATCH')}><Text name="reason" label="Lý do"/><button disabled={busy}>{m.enabled?'Tắt model':'Bật model'}</button></form></td></tr>)}</tbody></table></div>}
 <section className="panel"><h2>Cấp hoặc thu hồi quyền model</h2><form onSubmit={e=>submit(e,'/platform/grants',f=>({workspaceId:f.get('workspaceId'),modelId:f.get('modelId'),capability:f.get('capability'),active:f.get('active')==='true',reason:f.get('reason')}))}><fieldset disabled={busy||!data.models.length}><Text name="workspaceId" label="Workspace ID"/><label className="field">Model<select required name="modelId" value={modelId} onChange={e=>setModelId(e.target.value)}><option value="">Chọn model</option>{data.models.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><label className="field">Khả năng<select name="capability" required key={modelId}>{data.models.find(m=>m.id===modelId)?.capabilities.map(c=><option key={c}>{c}</option>)}</select></label><label className="field">Trạng thái<select name="active"><option value="true">Cấp quyền</option><option value="false">Thu hồi</option></select></label><Text name="reason" label="Lý do"/><button className="primary">Lưu quyền model</button></fieldset></form></section>
 <Lifecycle/><SupportViewer/><h2>Quyền đã cấu hình</h2>{!data.grants.length?<p>Chưa có quyền model.</p>:<div className="table-wrap"><table><thead><tr><th>Workspace</th><th>Model</th><th>Khả năng</th><th>Trạng thái</th></tr></thead><tbody>{data.grants.map(g=><tr key={g.id}><td>{g.workspace_id}</td><td>{data.models.find(m=>m.id===g.model_id)?.name}</td><td>{g.capability}</td><td>{g.active?'Đã cấp':'Đã thu hồi'}</td></tr>)}</tbody></table></div>}</>}</main></div>;
}
