ALTER TABLE web_sources ADD COLUMN IF NOT EXISTS max_bytes integer NOT NULL DEFAULT 5000000 CHECK(max_bytes BETWEEN 1 AND 20000000);
ALTER TABLE web_sources ADD COLUMN IF NOT EXISTS timeout_ms integer NOT NULL DEFAULT 10000 CHECK(timeout_ms BETWEEN 100 AND 60000);
ALTER TABLE web_sources ADD COLUMN IF NOT EXISTS max_redirects integer NOT NULL DEFAULT 5 CHECK(max_redirects BETWEEN 0 AND 5);
