import type {PoolClient} from 'pg';
import {z} from 'zod';
import {audit,HttpError,requireRole,uuid} from './security';

const field=z.object({key:z.string().trim().regex(/^[a-z][a-z0-9_]{0,49}$/),label:z.string().trim().min(1).max(120),description:z.string().trim().max(500).default(''),required:z.boolean().default(false),collect:z.boolean().default(true),type:z.enum(['text','email','phone']).default('text')}).strict();
const config=z.object({requestId:z.string().uuid(),completionLabel:z.string().trim().min(1).max(120),destination:z.enum(['OFF','GOOGLE_SHEETS','LARK_BITABLE']).default('OFF'),fields:z.array(field).max(50)}).strict();
const complete=z.object({requestId:z.string().uuid(),visitorKey:z.string().trim().min(1).max(200),values:z.record(z.string(),z.string().trim().max(2000))}).strict();
function normalizeFields(fields:any[]){const seen=new Set<string>(); return fields.map(f=>{if(seen.has(f.key))throw new HttpError(400,'VALIDATION_ERROR');seen.add(f.key);return {...f,description:f.description??'',required:!!f.required,collect:f.collect!==false,type:f.type??'text'};});}
async function replay(db:PoolClient,workspace:string,requestId:string,operation:string,payload:unknown){await db.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[`data-collection:${workspace}:${requestId}`]);const r=(await db.query('SELECT operation,payload=$3::jsonb AS same,response FROM data_collection_mutations WHERE workspace_id=$1 AND request_id=$2',[workspace,requestId,payload])).rows[0];if(r){if(r.operation!==operation||!r.same)throw new HttpError(409,'IDEMPOTENCY_CONFLICT');return r.response;}}
async function saveReplay(db:PoolClient,workspace:string,requestId:string,operation:string,payload:unknown,response:any){await db.query('INSERT INTO data_collection_mutations(workspace_id,request_id,operation,payload,response) VALUES($1,$2,$3,$4,$5)',[workspace,requestId,operation,payload,response]);return response;}
async function read(db:PoolClient,workspace:string){return (await db.query('SELECT id,workspace_id,completion_label AS "completionLabel",destination,state,fields,updated_at AS "updatedAt" FROM data_collection_configs WHERE workspace_id=$1',[workspace])).rows[0]??null;}
export async function getDataCollectionConfig(db:PoolClient,actor:any){requireRole(actor.role);return read(db,actor.workspace_id);}
export async function saveDataCollectionConfig(db:PoolClient,actor:any,body:unknown){requireRole(actor.role);const d=config.parse(body);const fields=normalizeFields(d.fields);const payload={...d,fields};const old=await replay(db,actor.workspace_id,d.requestId,'data_collection.config_saved',payload);if(old)return old;const state=fields.some(f=>f.collect)?'COLLECTING':'MISSING';const existing=(await db.query('SELECT id FROM data_collection_configs WHERE workspace_id=$1 FOR UPDATE',[actor.workspace_id])).rows[0];const id=existing?.id??uuid();await db.query(existing?'UPDATE data_collection_configs SET completion_label=$1,destination=$2,state=$3,fields=$4,updated_by=$5,updated_at=now() WHERE workspace_id=$6':'INSERT INTO data_collection_configs(id,workspace_id,completion_label,destination,state,fields,created_by,updated_by) VALUES($1,$2,$3,$4,$5,$6,$7,$7)',existing?[d.completionLabel,d.destination,state,JSON.stringify(fields),actor.user_id,actor.workspace_id]:[id,actor.workspace_id,d.completionLabel,d.destination,state,JSON.stringify(fields),actor.user_id]);await audit(db,actor.workspace_id,actor.user_id,'data_collection.config_saved',id);return saveReplay(db,actor.workspace_id,d.requestId,'data_collection.config_saved',payload,await read(db,actor.workspace_id));}
export async function completeDataCollection(db:PoolClient,workspace:string,body:unknown){const d=complete.parse(body);const cfg=await read(db,workspace);if(!cfg||cfg.state!=='COLLECTING')throw new HttpError(409,'COLLECTION_NOT_ACTIVE');const old=await replay(db,workspace,d.requestId,'data_collection.completed',{...d,values:d.values});if(old)return old;const fields:any[]=cfg.fields;for(const f of fields.filter(f=>f.collect&&f.required))if(!d.values[f.key])throw new HttpError(400,'REQUIRED_FIELD');const invalid=Object.keys(d.values).some(k=>!fields.some(f=>f.collect&&f.key===k));if(invalid)throw new HttpError(400,'VALIDATION_ERROR');const id=uuid();const inserted=await db.query('INSERT INTO data_collection_completions(id,workspace_id,config_id,visitor_key,values) VALUES($1,$2,$3,$4,$5) ON CONFLICT(workspace_id,config_id,visitor_key) DO NOTHING RETURNING id',[id,workspace,cfg.id,d.visitorKey,JSON.stringify(d.values)]);const completionId=inserted.rows[0]?.id;if(completionId&&cfg.destination!=='OFF')await db.query('INSERT INTO data_collection_outbox(id,workspace_id,completion_id,destination) VALUES($1,$2,$3,$4)',[uuid(),workspace,completionId,cfg.destination]);const response={completed:Boolean(completionId),duplicate:!completionId,completionId:completionId??null};return saveReplay(db,workspace,d.requestId,'data_collection.completed',{...d,values:d.values},response);}
