import React, { useState } from 'react';

export const AnalyticsView: React.FC = () => {
  const [range, setRange] = useState<'7d' | '30d' | 'quarter'>('7d');

  return (
    <main className="flex-1 overflow-y-auto px-6 py-6 space-y-6 bg-[#faf8ff] text-xs">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-[#c7c4d8]/60 pb-6">
        <div>
          <h1 className="text-xl md:text-2xl font-bold text-[#131b2e] tracking-tight">
            Support Telemetry & AI Analytics
          </h1>
          <p className="text-[#464555] mt-1">
            Real-time tracking of SLA benchmarks, agent concurrency, RAG retrieval grounding, and deflection rates.
          </p>
        </div>

        <div className="flex items-center gap-1.5 bg-[#eaedff] p-1 rounded-lg">
          <button
            onClick={() => setRange('7d')}
            className={`px-3 py-1 rounded text-xs font-semibold ${
              range === '7d' ? 'bg-white text-[#3525cd] shadow-xs' : 'text-[#464555]'
            }`}
          >
            Last 7 Days
          </button>
          <button
            onClick={() => setRange('30d')}
            className={`px-3 py-1 rounded text-xs font-semibold ${
              range === '30d' ? 'bg-white text-[#3525cd] shadow-xs' : 'text-[#464555]'
            }`}
          >
            Last 30 Days
          </button>
          <button
            onClick={() => setRange('quarter')}
            className={`px-3 py-1 rounded text-xs font-semibold ${
              range === 'quarter' ? 'bg-white text-[#3525cd] shadow-xs' : 'text-[#464555]'
            }`}
          >
            Quarterly
          </button>
        </div>
      </div>

      {/* 4 Metric Cards */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        <div className="p-4 rounded-xl bg-white border border-[#c7c4d8]/70 shadow-xs">
          <p className="text-[11px] font-bold uppercase tracking-wider text-[#777587]">
            Average Response SLA
          </p>
          <p className="text-2xl font-bold text-[#131b2e] mt-1 font-mono">42.4s</p>
          <p className="text-emerald-700 font-semibold mt-1 flex items-center gap-1">
            <span className="material-symbols-outlined text-[15px]">timer</span>
            <span>Target: &lt; 60s benchmark met</span>
          </p>
        </div>

        <div className="p-4 rounded-xl bg-white border border-[#c7c4d8]/70 shadow-xs">
          <p className="text-[11px] font-bold uppercase tracking-wider text-[#777587]">
            Customer Satisfaction (CSAT)
          </p>
          <p className="text-2xl font-bold text-[#131b2e] mt-1 font-mono">98.4%</p>
          <p className="text-emerald-700 font-semibold mt-1 flex items-center gap-1">
            <span className="material-symbols-outlined text-[15px]">trending_up</span>
            <span>+2.1% vs last week</span>
          </p>
        </div>

        <div className="p-4 rounded-xl bg-white border border-[#c7c4d8]/70 shadow-xs">
          <p className="text-[11px] font-bold uppercase tracking-wider text-[#777587]">
            AI Grounded Deflection
          </p>
          <p className="text-2xl font-bold text-[#3525cd] mt-1 font-mono">76.2%</p>
          <p className="text-[#464555] mt-1">1,082 inquiries handled autonomously</p>
        </div>

        <div className="p-4 rounded-xl bg-white border border-[#c7c4d8]/70 shadow-xs">
          <p className="text-[11px] font-bold uppercase tracking-wider text-[#777587]">
            RAG Grounding Accuracy
          </p>
          <p className="text-2xl font-bold text-emerald-700 mt-1 font-mono">99.96%</p>
          <p className="text-emerald-700 font-semibold mt-1 flex items-center gap-1">
            <span className="material-symbols-outlined text-[15px]">verified</span>
            <span>RLS shielded isolation</span>
          </p>
        </div>
      </div>

      {/* RAG Knowledge Retrieval Citations Table */}
      <div className="bg-white border border-[#c7c4d8]/70 rounded-xl p-5 shadow-xs space-y-4">
        <div className="flex items-center justify-between">
          <div>
            <h3 className="text-sm font-bold text-[#131b2e]">
              Top Cited Documents in RAG Inferences
            </h3>
            <p className="text-[#464555] text-xs">
              Direct telemetry citations generated by GoTek Copilot for customer chats.
            </p>
          </div>
          <span className="font-mono text-[11px] text-[#3525cd] bg-[#eaedff] px-2 py-0.5 rounded font-bold">
            1536-Dimensional Embeddings
          </span>
        </div>

        <div className="divide-y divide-[#eaedff]">
          {[
            {
              title: 'GoTek_Enterprise_Sec_Architecture_v4.pdf',
              queries: 842,
              avgSim: '0.96',
              category: 'Security & Infrastructure',
            },
            {
              title: 'Compliance_PCI_DSS_Attestation_2024.pdf',
              queries: 610,
              avgSim: '0.93',
              category: 'Regulatory Compliance',
            },
            {
              title: 'Chinh_sach_gia_Enterprise_v2.pdf',
              queries: 480,
              avgSim: '0.91',
              category: 'Pricing & Tiers',
            },
            {
              title: 'Quy_trinh_ky_ket_NDA_2024.docx',
              queries: 390,
              avgSim: '0.89',
              category: 'Legal Agreements',
            },
          ].map((item, i) => (
            <div key={i} className="py-3 flex items-center justify-between">
              <div className="flex items-center gap-3">
                <span className="w-6 h-6 rounded bg-[#eaedff] text-[#3525cd] font-bold flex items-center justify-center font-mono">
                  {i + 1}
                </span>
                <div>
                  <p className="font-semibold text-xs text-[#131b2e]">{item.title}</p>
                  <p className="text-[11px] text-[#777587]">{item.category}</p>
                </div>
              </div>
              <div className="flex items-center gap-6 font-mono text-xs">
                <div className="text-right">
                  <p className="font-bold text-[#131b2e]">{item.queries} citations</p>
                  <p className="text-[10px] text-emerald-700">Cosine Avg: {item.avgSim}</p>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </main>
  );
};
