import test from 'node:test';
import assert from 'node:assert/strict';
import request from 'supertest';
import {randomUUID} from 'node:crypto';
import {createApp} from '../src/server/app';
import {pool,transaction,scope} from '../src/server/db';
import {createKnowledge,updateKnowledge,listKnowledge} from '../src/server/knowledge';
test('H10 draft storage: unicode, immutable versions, replay, conflict, pagination and tenant isolation',async t=>{
 t.after(()=>pool.end());const app=createApp();
 async function owner(){const a=request.agent(app),email=`knowledge-${randomUUID()}@example.test`,password='Local-knowledge-2026';await a.post('/api/auth/signup').set('X-Gotek-Request','1').send({email,password,fullName:'Knowledge test',business:'Knowledge local',phone:'0900000000'}).expect(202);await a.post('/api/auth/login').set('X-Gotek-Request','1').send({email,password}).expect(200);const me=(await a.get('/api/me').expect(200)).body;return {user_id:me.user.id,workspace_id:me.workspaceId,role:'Owner'};}
 const actor=await owner(),other=await owner();
 const run=(fn:any,a=actor)=>transaction(async db=>{await scope(db,a.workspace_id);return fn(db,a);});
 const body={requestId:randomUUID(),title:'😀'.repeat(100),content:'ế'.repeat(2000)};
 const results:any[]=await Promise.all(Array.from({length:4},()=>run((db:any,a:any)=>createKnowledge(db,a,body))));const first=results[0];assert.equal(new Set(results.map(x=>x.id)).size,1);assert.equal(first.published_version_id,null);assert.equal(first.audience,'INTERNAL');
 await assert.rejects(run((db:any,a:any)=>createKnowledge(db,a,{...body,title:'Changed'})),(e:any)=>e.code==='IDEMPOTENCY_CONFLICT');
 for(const invalid of [{title:'😀'.repeat(101)},{content:'😀'.repeat(2001)},{title:' \n '}])await assert.rejects(run((db:any,a:any)=>createKnowledge(db,a,{...body,requestId:randomUUID(),...invalid})),(e:any)=>e.name==='ZodError');
 await assert.rejects(run((db:any,a:any)=>createKnowledge(db,a,{...body,requestId:randomUUID(),categoryId:randomUUID()})),(e:any)=>e.code==='NOT_FOUND');
 const edit={requestId:randomUUID(),expectedRevision:1,title:'Tiếng Việt',content:'Nội dung\nxuống dòng'};
 const second:any=await run((db:any,a:any)=>updateKnowledge(db,a,first.id,edit));assert.equal(second.revision,2);assert.notEqual(second.draft_version_id,first.draft_version_id);
 assert.equal((await run((db:any,a:any)=>updateKnowledge(db,a,first.id,edit)) as any).revision,2);
 await assert.rejects(run((db:any,a:any)=>updateKnowledge(db,a,first.id,{...edit,requestId:randomUUID()})),(e:any)=>e.code==='VERSION_CONFLICT');
 await run(async(db:any)=>{const versions=(await db.query('SELECT title FROM knowledge_versions WHERE item_id=$1 ORDER BY version_no',[first.id])).rows;assert.deepEqual(versions.map((v:any)=>v.title),[body.title,edit.title]);assert.equal(Number((await db.query('SELECT count(*) FROM audit_events WHERE object_id=$1',[first.id])).rows[0].count),2);});
 const competing=await Promise.allSettled([1,2].map(n=>run((db:any,a:any)=>updateKnowledge(db,a,first.id,{requestId:randomUUID(),expectedRevision:2,title:`Race ${n}`,content:'Only one revision wins'}))));
 assert.equal(competing.filter(x=>x.status==='fulfilled').length,1);assert.equal(competing.filter(x=>x.status==='rejected'&&(x.reason as any).code==='VERSION_CONFLICT').length,1);
 await run(async(db:any,a:any)=>{assert.equal((await listKnowledge(db,a,{})).items.length,0);assert.equal((await db.query('SELECT id FROM knowledge_versions WHERE item_id=$1',[first.id])).rows.length,0);},other);
 await assert.rejects(run((db:any,a:any)=>updateKnowledge(db,a,first.id,{...edit,requestId:randomUUID(),expectedRevision:2}),other),(e:any)=>e.code==='NOT_FOUND');
 await assert.rejects(run((db:any,a:any)=>listKnowledge(db,{...a,role:'Agent'},{})),(e:any)=>e.code==='FORBIDDEN');
 for(let i=0;i<3;i++)await run((db:any,a:any)=>createKnowledge(db,a,{requestId:randomUUID(),title:`Page ${i}`,content:'Data',active:false}));
 const ids:string[]=[];let cursor: string|undefined;do{const page:any=await run((db:any,a:any)=>listKnowledge(db,a,{limit:'1',cursor,sort:'oldest'}));ids.push(...page.items.map((i:any)=>i.id));cursor=page.nextCursor||undefined;}while(cursor);assert.equal(ids.length,4);assert.equal(new Set(ids).size,4);
 assert.equal((await run((db:any,a:any)=>listKnowledge(db,a,{active:'false',search:'Page'})) as any).items.length,3);
});
