import assert from 'node:assert/strict';
import {test} from 'node:test';
import request from 'supertest';
import {randomUUID} from 'node:crypto';
import {createApp} from '../src/server/app';
import {pool} from '../src/server/db';

test('H09 rules export/import is tenant scoped and auditable', async (t) => {
  t.after(async()=>{await pool.end();});
  const app = createApp();
  const agent = request.agent(app);
  const email = `transfer-${randomUUID()}@example.test`;
  const password = 'Transfer-test-password-2026';
  await agent.post('/api/auth/signup').set('X-Gotek-Request','1').send({email,password,fullName:'Transfer owner',business:'Transfer workspace',phone:'0900000000'}).expect(202);
  await agent.post('/api/auth/login').set('X-Gotek-Request','1').send({email,password}).expect(200);
  const created = await agent.post('/api/ai/rules').set('X-Gotek-Request','1').send({title:'Export me',content:'Keep it portable'}).expect(200);
  const exported = await agent.get('/api/ai/rules/export').expect(200);
  assert.equal(exported.body.format, 'gotek-ai-rules');
  assert.equal(exported.body.rules.some((r: any) => r.title === 'Export me'), true);
  assert.equal(exported.body.rules[0].id, undefined);
  const roundtrip = await agent.post('/api/ai/rules/import').set('X-Gotek-Request','1').send(exported.body).expect(200);
  assert.equal(roundtrip.body.imported, 1);
  assert.equal(roundtrip.body.rules[0].title, 'Export me');
  assert.notEqual(roundtrip.body.rules[0].id, created.body.id);
  await agent.post('/api/ai/rules/import').set('X-Gotek-Request','1').send({...exported.body,version:2}).expect(400);
  const imported = await agent.post('/api/ai/rules/import').set('X-Gotek-Request','1').send({format:'gotek-ai-rules',rules:[{title:'Imported',content:'Imported body',active:false}]}).expect(200);
  assert.equal(imported.body.imported, 1);
  assert.equal(imported.body.rules[0].active, false);
  assert.notEqual(imported.body.rules[0].id, created.body.id);
  assert.equal((await agent.get('/api/audit')).body.some((x:any)=>x.object_id===imported.body.rules[0].id&&x.action==='ai_rule.imported'), true);
  const beforeRules=(await agent.get('/api/ai/rules/export').expect(200)).body.rules;
  const beforeAudit=(await agent.get('/api/audit').expect(200)).body;
  const invalid=await agent.post('/api/ai/rules/import').set('X-Gotek-Request','1').send({rules:[{title:'Valid first row',content:'Must not persist'},{title:'',content:'Invalid second row'}]}).expect(400);
  assert.equal(invalid.body.error,'VALIDATION');
  assert.deepEqual((await agent.get('/api/ai/rules/export')).body.rules,beforeRules);
  assert.deepEqual((await agent.get('/api/audit')).body,beforeAudit);
  await agent.post('/api/ai/rules/import').set('X-Gotek-Request','1').send({rules:[{id:created.body.id,title:'Foreign ID',content:'Reject'}]}).expect(400);
  const other=request.agent(app),otherEmail=`transfer-other-${randomUUID()}@example.test`;
  await other.post('/api/auth/signup').set('X-Gotek-Request','1').send({email:otherEmail,password,fullName:'Other owner',business:'Other workspace',phone:'0900000000'}).expect(202);
  await other.post('/api/auth/login').set('X-Gotek-Request','1').send({email:otherEmail,password}).expect(200);
  assert.deepEqual((await other.get('/api/ai/rules/export').expect(200)).body.rules,[]);
  await other.post('/api/ai/rules/import').set('X-Gotek-Request','1').send({rules:[{title:'Other workspace rule',content:'Isolated'}]}).expect(200);
  assert.deepEqual((await agent.get('/api/ai/rules/export')).body.rules,beforeRules);
  const ids = (await pool.query('SELECT u.id user_id,m.workspace_id FROM users u JOIN memberships m ON m.user_id=u.id WHERE u.email=$1', [email])).rows[0];
  await pool.query('DELETE FROM ai_rules WHERE workspace_id=$1', [ids.workspace_id]);
});
