import test from 'node:test';
import assert from 'node:assert/strict';
import request from 'supertest';
import {randomUUID} from 'node:crypto';
import {runWebRefreshOnce} from '../src/server/web-refresh-worker';
import {createApp} from '../src/server/app';
import {pool,transaction,scope} from '../src/server/db';

test('H11 configuration persists, audits and isolates two workspaces',async(t)=>{
 t.after(async()=>{await pool.end();});
 const app=createApp();
 async function owner(){const agent=request.agent(app),email=`web-${randomUUID()}@example.test`,password='Local-web-source-test-2026';
 await agent.post('/api/auth/signup').set('X-Gotek-Request','1').send({email,password,fullName:'Local source tester',business:'Test sources',phone:'0900000000'}).expect(202);
 await agent.post('/api/auth/login').set('X-Gotek-Request','1').send({email,password}).expect(200);return agent;}
 const a=await owner(),b=await owner();
 const created=await a.post('/api/web-sources').set('X-Gotek-Request','1').send({name:'Example source',url:'https://example.com/docs',type:'URL'}).expect(200);
 assert.equal(created.body.max_pages,20);assert.equal(created.body.depth,2);
 assert.equal((await a.get('/api/web-sources').expect(200)).body[0].id,created.body.id);
 assert.deepEqual((await b.get('/api/web-sources').expect(200)).body,[]);
 await b.patch(`/api/web-sources/${created.body.id}/status`).set('X-Gotek-Request','1').send({status:'PAUSED'}).expect(404);
 await a.patch('/api/web-sources/invalid/status').set('X-Gotek-Request','1').send({status:'PAUSED'}).expect(400);
 await b.post(`/api/web-sources/${created.body.id}/preview`).set('X-Gotek-Request','1').send({}).expect(404);
 await a.post('/api/web-sources/invalid/preview').set('X-Gotek-Request','1').send({}).expect(400);
 await request(app).post(`/api/web-sources/${created.body.id}/preview`).set('X-Gotek-Request','1').send({}).expect(401);
 assert.deepEqual((await a.get(`/api/web-sources/${created.body.id}/snapshots`).expect(200)).body,[]);
 await b.get(`/api/web-sources/${created.body.id}/snapshots`).expect(404);
 await request(app).get(`/api/web-sources/${created.body.id}/snapshots`).expect(401);
 await a.get(`/api/web-sources/${created.body.id}/snapshots/${randomUUID()}`).expect(404);
 const scheduleUrl=`/api/web-sources/${created.body.id}/schedule`;
 const initial=(await a.get(scheduleUrl).expect(200)).body;
 assert.equal(initial.refresh_interval_minutes,null);assert.equal(initial.schedule_version,1);
 await b.get(scheduleUrl).expect(404);await request(app).get(scheduleUrl).expect(401);
 await b.patch(scheduleUrl).set('X-Gotek-Request','1').send({version:1,intervalMinutes:30}).expect(404);
 await a.patch(scheduleUrl).set('X-Gotek-Request','1').send({version:1,intervalMinutes:1}).expect(400);
 const configured=(await a.patch(scheduleUrl).set('X-Gotek-Request','1').send({version:1,intervalMinutes:30}).expect(200)).body;
 assert.equal(configured.schedule_version,2);assert.equal(configured.refresh_interval_minutes,30);assert.ok(configured.next_refresh_at);
 assert.deepEqual((await a.get(scheduleUrl).expect(200)).body,configured);
 await a.patch(scheduleUrl).set('X-Gotek-Request','1').send({version:1,intervalMinutes:null}).expect(409);
 const disabled=(await a.patch(scheduleUrl).set('X-Gotek-Request','1').send({version:2,intervalMinutes:null}).expect(200)).body;
 assert.equal(disabled.next_refresh_at,null);
 assert.equal((await a.get('/api/audit').expect(200)).body.filter((e:any)=>e.action==='web_source.schedule_changed'&&e.object_id===created.body.id).length,2);
 const refreshId=randomUUID();
 const refresh=()=>a.post(`/api/web-sources/${created.body.id}/refresh`).set('X-Gotek-Request','1').send({requestId:refreshId});
 const queued=await Promise.all([refresh().expect(200),refresh().expect(200)]);
 assert.equal(queued[0].body.jobId,queued[1].body.jobId);assert.equal(queued[0].body.state,'queued');
 await b.post(`/api/web-sources/${created.body.id}/refresh`).set('X-Gotek-Request','1').send({requestId:refreshId}).expect(404);
 await request(app).post(`/api/web-sources/${created.body.id}/refresh`).set('X-Gotek-Request','1').send({requestId:refreshId}).expect(401);
 assert.equal((await a.get('/api/audit').expect(200)).body.filter((e:any)=>e.action==='web_source.refresh_requested'&&e.object_id===created.body.id).length,1);
 const tenant=(await a.get('/api/me').expect(200)).body.workspaceId;
 let fetchCalls=0;
 await runWebRefreshOnce(tenant,async()=>{fetchCalls++;return {url:'https://example.com/docs',status:200,contentType:'text/html',body:Buffer.from('<html><title>Enterprise guide</title><body><p>Warranty lasts twelve months.</p></body></html>')};});
 assert.equal(fetchCalls,1);
 const history=(await a.get(`/api/web-sources/${created.body.id}/snapshots`).expect(200)).body;
 assert.equal(history.length,1);assert.equal(history[0].job_id,queued[0].body.jobId);
 assert.equal(history[0].document,undefined);
 const snapshot=(await a.get(`/api/web-sources/${created.body.id}/snapshots/${history[0].id}`).expect(200)).body;
 assert.match(JSON.stringify(snapshot.document),/Warranty lasts twelve months/);
 await b.get(`/api/web-sources/${created.body.id}/snapshots/${history[0].id}`).expect(404);
 await request(app).get(`/api/web-sources/${created.body.id}/snapshots/${history[0].id}`).expect(401);
 assert.equal((await refresh().expect(200)).body.state,'succeeded');
 const importUrl=`/api/web-sources/${created.body.id}/snapshots/${history[0].id}/knowledge-drafts`;
 const draftBody={itemIndex:0,title:'Warranty source'};
 const drafts=await Promise.all([a.post(importUrl).set('X-Gotek-Request','1').send(draftBody).expect(200),a.post(importUrl).set('X-Gotek-Request','1').send(draftBody).expect(200)]);
 assert.deepEqual(drafts[0].body,drafts[1].body);assert.equal(drafts[0].body.items[0].state,'DRAFT');
 assert.equal((await a.get('/api/audit').expect(200)).body.filter((e:any)=>e.action==='knowledge.web_imported'&&e.object_id===history[0].id).length,1);
 const webItems=(await a.get('/api/knowledge/items?source=WEB').expect(200)).body.items;
 assert.equal(webItems.length,1);assert.equal(webItems[0].audience,'INTERNAL');assert.equal(webItems[0].published_version_id,null);
 assert.equal((await a.get('/api/knowledge/items?source=MANUAL').expect(200)).body.items.length,0);
 const generationDraftUrl=`/api/web-sources/${created.body.id}/snapshots/${history[0].id}/generation-draft`;
 const generationRequestId=randomUUID();
 const generationDraft=await a.post(generationDraftUrl).set('X-Gotek-Request','1').send({requestId:generationRequestId,itemIndex:0,title:'Warranty source'}).expect(200);
 assert.equal(generationDraft.body.state,'DRAFT');
 assert.ok(generationDraft.body.generationId);
 assert.ok(generationDraft.body.groupId);
 const generationReplay=await a.post(generationDraftUrl).set('X-Gotek-Request','1').send({requestId:generationRequestId,itemIndex:0,title:'Warranty source'}).expect(200);
 assert.equal(generationReplay.body.generationId,generationDraft.body.generationId);
 assert.equal(generationReplay.body.groupId,generationDraft.body.groupId);
 assert.equal(generationReplay.body.replayed,true);
 await b.post(generationDraftUrl).set('X-Gotek-Request','1').send({requestId:randomUUID(),itemIndex:0,title:'Cross tenant'}).expect(404);
 await request(app).post(generationDraftUrl).set('X-Gotek-Request','1').send({requestId:randomUUID(),itemIndex:0,title:'Anonymous'}).expect(401);
 await a.post(importUrl).set('X-Gotek-Request','1').send({...draftBody,title:'Changed'}).expect(409);
 await b.post(importUrl).set('X-Gotek-Request','1').send(draftBody).expect(404);
 await request(app).post(importUrl).set('X-Gotek-Request','1').send(draftBody).expect(401);

 const paused=await a.patch(`/api/web-sources/${created.body.id}/status`).set('X-Gotek-Request','1').send({status:'PAUSED'}).expect(200);
 assert.equal(paused.body.status,'PAUSED');
 await refresh().expect(409);
 const previewDenied=await a.post(`/api/web-sources/${created.body.id}/preview`).set('X-Gotek-Request','1').send({}).expect(409);
 assert.equal(previewDenied.body.error,'SOURCE_PAUSED');
 assert.ok(!(await a.get('/api/audit')).body.some((e:any)=>e.object_id===created.body.id&&e.action==='web_source.previewed'));
 assert.equal((await a.get('/api/web-sources')).body[0].status,'PAUSED');
 await a.post('/api/web-sources').set('X-Gotek-Request','1').send({name:'Blocked',url:'http://127.0.0.1/',type:'URL'}).expect(400);
 await a.post('/api/web-sources').set('X-Gotek-Request','1').send({name:'Too many',url:'https://example.com/',type:'RSS',maxPages:21}).expect(400);
 assert.ok((await a.get('/api/audit')).body.some((e:any)=>e.object_id===created.body.id&&e.action==='web_source.paused'));
 // Modify only the newly created fixture membership; existing sessions must obey current role.
 const me=(await a.get('/api/me').expect(200)).body;
 await transaction(async db=>{await scope(db,me.workspaceId);await db.query("UPDATE memberships SET role='Agent' WHERE workspace_id=$1 AND user_id=$2",[me.workspaceId,me.user.id]);});
 await a.get('/api/web-sources').expect(403);
 await a.post(`/api/web-sources/${created.body.id}/preview`).set('X-Gotek-Request','1').send({}).expect(403);
 await a.post('/api/web-sources').set('X-Gotek-Request','1').send({name:'Denied',url:'https://example.com/',type:'URL'}).expect(403);
 await a.patch(`/api/web-sources/${created.body.id}/status`).set('X-Gotek-Request','1').send({status:'ACTIVE'}).expect(403);
 await transaction(async db=>{await scope(db,me.workspaceId);assert.equal((await db.query('SELECT status FROM web_sources WHERE id=$1',[created.body.id])).rows[0].status,'PAUSED');await db.query("UPDATE memberships SET role='Owner' WHERE workspace_id=$1 AND user_id=$2",[me.workspaceId,me.user.id]);});

});
