import {WidgetPreview} from './WidgetPreview';
import {useEffect,useState} from 'react';
import {api} from '@/api/api';
const weekdays=['Chủ nhật','Thứ hai','Thứ ba','Thứ tư','Thứ năm','Thứ sáu','Thứ bảy'];
export function ChannelConfiguration({initial,onClose}:{initial:any,onClose:()=>void}){
 const [value,setValue]=useState(()=>({...initial,business_hours:{...initial.business_hours,days:weekdays.map((_,day)=>initial.business_hours.days.find((d:any)=>d.day===day)||{day,enabled:false,fullDay:false,start:'09:00',end:'17:00'})},prechat:{...initial.prechat,fields:['emailAddress','fullName','phoneNumber'].map((key,i)=>initial.prechat.fields.find((f:any)=>f.key===key)||{key,enabled:false,required:false,label:['Email','Họ tên','Số điện thoại'][i],placeholder:''})}}));
 const [busy,setBusy]=useState(false),[savingAgents,setSavingAgents]=useState(false),[message,setMessage]=useState(''),[agentMessage,setAgentMessage]=useState(''),[error,setError]=useState(''),[members,setMembers]=useState<any[]>([]),[agents,setAgents]=useState<string[]>([]);
 useEffect(()=>{Promise.all([api('/members'),api(`/channels/${initial.id}/agents`)]).then(([all,current])=>{setMembers(all.filter((m:any)=>m.active));setAgents(current.map((m:any)=>m.id));}).catch(e=>setError((e as Error).message));},[initial.id]);
 function hours(patch:any){setValue({...value,business_hours:{...value.business_hours,...patch}});}
 function field(index:number,patch:any){setValue({...value,prechat:{...value.prechat,fields:value.prechat.fields.map((f:any,i:number)=>i===index?{...f,...patch}:f)}});}
 async function saveAgents(){if(!agents.length){setError('Chọn ít nhất một cộng tác viên.');return;}setSavingAgents(true);setError('');setAgentMessage('');try{await api(`/channels/${value.id}/agents`,'PUT',{agents});const current=await api(`/channels/${value.id}/agents`);setAgents(current.map((m:any)=>m.id));setAgentMessage('Đã lưu cộng tác viên và đọc lại.');}catch(e){setError((e as Error).message);}finally{setSavingAgents(false);}}
 async function save(){setBusy(true);setError('');setMessage('');try{await api(`/channels/${value.id}/settings`,'PATCH',{assignmentEnabled:value.assignment_enabled,assignmentLimit:value.assignment_limit,businessHours:value.business_hours,prechat:value.prechat,widgetTitle:value.widget_title,widgetPosition:value.widget_position,widgetMode:value.widget_mode});const saved=await api(`/channels/${value.id}/settings`);setValue({...value,...saved});setMessage('Đã lưu và đọc lại cấu hình.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="panel"><h2>Cấu hình {initial.name}</h2>{error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}<form onSubmit={e=>{e.preventDefault();void save();}}><fieldset disabled={busy}>
 <h3>Cộng tác viên</h3><p>Chỉ thành viên đang hoạt động trong workspace được nhận hội thoại.</p>{members.map(m=><label className="field" key={m.id}><span><input type="checkbox" checked={agents.includes(m.id)} onChange={e=>setAgents(e.target.checked?[...agents,m.id]:agents.filter(id=>id!==m.id))}/>{m.full_name} · {m.role}</span></label>)}{agentMessage&&<p role="status">{agentMessage}</p>}<button type="button" onClick={()=>void saveAgents()} disabled={busy||savingAgents}>{savingAgents?'Đang lưu cộng tác viên…':'Lưu cộng tác viên'}</button><h3>Giờ làm việc</h3><label><input type="checkbox" checked={value.business_hours.enabled} onChange={e=>hours({enabled:e.target.checked})}/> Bật giờ làm việc</label><label className="field">Múi giờ<input required value={value.business_hours.timezone} onChange={e=>hours({timezone:e.target.value})}/></label>
 {value.business_hours.days.map((d:any,i:number)=><fieldset key={d.day} disabled={!value.business_hours.enabled}><legend>{weekdays[d.day]}</legend><label><input type="checkbox" checked={d.enabled} onChange={e=>hours({days:value.business_hours.days.map((x:any,j:number)=>j===i?{...x,enabled:e.target.checked}:x)})}/> Khả dụng</label><label><input type="checkbox" disabled={!d.enabled} checked={d.fullDay} onChange={e=>hours({days:value.business_hours.days.map((x:any,j:number)=>j===i?{...x,fullDay:e.target.checked}:x)})}/> Cả ngày</label>{(['start','end'] as const).map(k=><label className="field" key={k}>{k==='start'?'Bắt đầu':'Kết thúc'}<input type="time" required disabled={!d.enabled||d.fullDay} value={d[k]} onChange={e=>hours({days:value.business_hours.days.map((x:any,j:number)=>j===i?{...x,[k]:e.target.value}:x)})}/></label>)}</fieldset>)}
 <h3>Phân công</h3><label><input type="checkbox" checked={value.assignment_enabled} onChange={e=>setValue({...value,assignment_enabled:e.target.checked})}/> Tự động phân công</label><label className="field">Số hội thoại tối đa mỗi người<input type="number" min="1" max="100" disabled={!value.assignment_enabled} value={value.assignment_limit??''} onChange={e=>setValue({...value,assignment_limit:e.target.value===''?null:Number(e.target.value)})}/></label>
 <h3>Biểu mẫu trước khi trò chuyện</h3><label><input type="checkbox" checked={value.prechat.enabled} onChange={e=>setValue({...value,prechat:{...value.prechat,enabled:e.target.checked,fields:value.prechat.fields.map((f:any)=>f.enabled?f:{...f,required:false})}})}/> Bật biểu mẫu</label><label className="field">Lời nhắn<textarea maxLength={500} value={value.prechat.message} onChange={e=>setValue({...value,prechat:{...value.prechat,message:e.target.value}})}/></label>
 {value.prechat.fields.map((f:any,i:number)=><fieldset key={f.key} disabled={!value.prechat.enabled}><legend>{f.key}</legend><label><input type="checkbox" checked={f.enabled} onChange={e=>field(i,{enabled:e.target.checked,...(!e.target.checked?{required:false}:{})})}/> Bật trường</label><label><input type="checkbox" disabled={!f.enabled} checked={f.required} onChange={e=>field(i,{required:e.target.checked})}/> Bắt buộc</label><label className="field">Nhãn<input disabled={!f.enabled} required maxLength={120} value={f.label} onChange={e=>field(i,{label:e.target.value})}/></label><label className="field">Gợi ý nhập<input disabled={!f.enabled} maxLength={160} value={f.placeholder} onChange={e=>field(i,{placeholder:e.target.value})}/></label></fieldset>)}
 <h3>Trình tạo widget</h3><label className="field">Tiêu đề launcher<input required maxLength={80} value={value.widget_title} onChange={e=>setValue({...value,widget_title:e.target.value})}/></label><label className="field">Vị trí<select value={value.widget_position} onChange={e=>setValue({...value,widget_position:e.target.value})}><option value="left">Trái</option><option value="right">Phải</option></select></label><label className="field">Kiểu<select value={value.widget_mode} onChange={e=>setValue({...value,widget_mode:e.target.value})}><option value="standard">Chuẩn</option><option value="expanded">Mở rộng</option></select></label>
 <WidgetPreview title={value.widget_title} position={value.widget_position} mode={value.widget_mode} name={initial.name}/>
 <button className="primary">{busy?'Đang lưu…':'Lưu cấu hình'}</button><button type="button" onClick={onClose}>Đóng</button></fieldset></form></section>;
}
