import {fixturePdf} from './fixtures/pdf';
import test from 'node:test';
import assert from 'node:assert/strict';
import request from 'supertest';
import {randomUUID} from 'node:crypto';
import {readFileSync} from 'node:fs';
import {createApp} from '../src/app';
import {pool,transaction,scope} from '../src/core/db';

test('H10 knowledge draft API persists edits, isolates tenants and enforces live membership',async(t)=>{
 t.after(()=>pool.end());const app=createApp();
 async function fixture(){const agent=request.agent(app),email=`knowledge-api-${randomUUID()}@example.test`,password='Local-knowledge-test-2026';
 await agent.post('/api/auth/signup').set('X-Gotek-Request','1').send({email,password,fullName:'Knowledge tester',business:'Knowledge test',phone:'0900000000'}).expect(202);
 await agent.post('/api/auth/login').set('X-Gotek-Request','1').send({email,password}).expect(200);return agent;}
 const a=await fixture(),b=await fixture(),send=(agent:any,path:string,body:any)=>agent.post(path).set('X-Gotek-Request','1').send(body);
 const categoryRequest={requestId:randomUUID(),name:'Sản phẩm'};
 const category=(await send(a,'/api/knowledge-categories',categoryRequest).expect(200)).body;
 assert.equal((await send(a,'/api/knowledge-categories',categoryRequest).expect(200)).body.id,category.id);
 await send(a,'/api/knowledge-categories',{requestId:randomUUID(),name:'SẢN PHẨM'}).expect(409);
 assert.deepEqual((await b.get('/api/knowledge-categories').expect(200)).body,[]);
 await send(b,'/api/knowledge/items',{requestId:randomUUID(),title:'Foreign',content:'Denied',categoryId:category.id}).expect(404);
 const payload={categoryId:category.id,requestId:randomUUID(),title:'Thông tin GoTek',content:'Dòng một\nDòng hai',active:true};
 const created=(await send(a,'/api/knowledge/items',payload).expect(200)).body;
 assert.equal(created.category_id,category.id);
 assert.equal((await a.get(`/api/knowledge/items?categoryId=${category.id}`)).body.items.length,1);

 assert.equal(created.title,payload.title);assert.equal(created.published_version_id,null);
 assert.equal((await send(a,'/api/knowledge/items',payload).expect(200)).body.id,created.id);
 await send(a,'/api/knowledge/items',{...payload,title:'Khác'}).expect(409);
 const preserved=(await a.patch(`/api/knowledge/items/${created.id}/draft`).set('X-Gotek-Request','1').send({requestId:randomUUID(),expectedRevision:created.revision,title:'Giữ danh mục',content:'Sửa nội dung'}).expect(200)).body;
 assert.equal(preserved.category_id,category.id);
 const edit={requestId:randomUUID(),expectedRevision:preserved.revision,title:'Mới',content:'Nội dung mới',categoryId:null};
 const updated=(await a.patch(`/api/knowledge/items/${created.id}/draft`).set('X-Gotek-Request','1').send(edit).expect(200)).body;
 assert.equal(updated.category_id,null);
 assert.equal(updated.revision,preserved.revision+1);
 assert.equal((await a.get('/api/knowledge/items').expect(200)).body.items[0].content,edit.content);
 assert.deepEqual((await b.get('/api/knowledge/items').expect(200)).body.items,[]);
 await b.patch(`/api/knowledge/items/${created.id}/draft`).set('X-Gotek-Request','1').send({...edit,requestId:randomUUID()}).expect(404);
 const me=(await a.get('/api/me')).body;
 const batch=(await send(a,'/api/knowledge/import',{items:[{requestId:randomUUID(),title:'FAQ một',content:'Câu trả lời một',categoryId:category.id},{requestId:randomUUID(),title:'FAQ hai',content:'Câu trả lời hai',categoryId:category.id}]}).expect(200)).body; assert.equal(batch.imported,2); assert.equal(batch.state,'DRAFT'); assert.equal((await a.get(`/api/knowledge/items?categoryId=${category.id}`)).body.items.length,2);
 const document=(await a.post('/api/knowledge/import-document').set('X-Gotek-Request','1').attach('file','tests/fixtures/enterprise-faq.docx').expect(200)).body;
 const importReceipt=(await a.get('/api/knowledge/imports/'+document.importId).expect(200)).body;
 assert.equal(importReceipt.status,'COMPLETED');
 assert.equal(importReceipt.filename,'enterprise-faq.docx');
 assert.equal(importReceipt.imported_count,document.imported);
 assert.match(importReceipt.content_hash,/^[0-9a-f]{64}$/);
 assert.ok(importReceipt.byte_size>0);
 await b.get('/api/knowledge/imports/'+document.importId).expect(404);
 const original=await a.get('/api/knowledge/imports/'+document.importId+'/file').expect(200);
 assert.deepEqual(original.body,readFileSync('tests/fixtures/enterprise-faq.docx'));
 assert.match(original.headers['content-disposition'],/^attachment;/);
 assert.equal(original.headers['cache-control'],'no-store');
 await b.get('/api/knowledge/imports/'+document.importId+'/file').expect(404);
 await request(app).get('/api/knowledge/imports/'+document.importId+'/file').expect(401);
 assert.equal(document.state,'DRAFT');assert.equal(document.imported,1);assert.match(document.items[0].content,/12 tháng/);
 const failedRequest=randomUUID();
 const failed=(await b.post('/api/knowledge/import-document').set('X-Gotek-Request','1').set('X-Gotek-Import-Id',failedRequest).attach('file',Buffer.from('invalid'),'invalid.docx').expect(400)).body;
 assert.equal(failed.error,'INVALID_DOCUMENT');
 const failedRetry=(await b.post('/api/knowledge/import-document').set('X-Gotek-Request','1').set('X-Gotek-Import-Id',failedRequest).attach('file',Buffer.from('invalid'),'invalid.docx').expect(400)).body;
 assert.deepEqual(failedRetry,failed);
 const failedHistory=(await b.get('/api/knowledge/imports').query({status:'FAILED'}).expect(200)).body.items;
 assert.equal(failedHistory.length,1);assert.equal(failedHistory[0].id,failed.importId);
 assert.equal(failedHistory[0].error_code,'INVALID_DOCUMENT');assert.equal(failedHistory[0].imported_count,0);
 assert.deepEqual((await b.get('/api/knowledge/items').expect(200)).body.items,[]);
 const pdf=(await a.post('/api/knowledge/import-document').set('X-Gotek-Request','1').attach('file',fixturePdf('Enterprise warranty 12 months'),'policy.pdf').expect(200)).body;
 const retry=(await a.post('/api/knowledge/import-document').set('X-Gotek-Request','1').set('X-Gotek-Import-Id',pdf.requestId).attach('file',fixturePdf('Enterprise warranty 12 months'),'policy.pdf').expect(200)).body;
 assert.equal(retry.importId,pdf.importId);
 assert.deepEqual(retry,pdf);
 const page=(await a.get('/api/knowledge/imports').query({limit:1,status:'COMPLETED'}).expect(200)).body;
 assert.equal(page.items[0].id,pdf.importId);
 assert.equal(page.nextCursor,pdf.importId);
 assert.equal(page.items[0].bytes,undefined);
 const next=(await a.get('/api/knowledge/imports').query({limit:1,cursor:page.nextCursor,status:'COMPLETED'}).expect(200)).body;
 assert.equal(next.items[0].id,document.importId);assert.equal(next.nextCursor,null);
 assert.deepEqual((await b.get('/api/knowledge/imports').query({status:'COMPLETED'}).expect(200)).body.items,[]);
 await b.get('/api/knowledge/imports').query({cursor:pdf.importId}).expect(400);
 assert.deepEqual((await a.get('/api/knowledge/imports').query({status:'FAILED'}).expect(200)).body.items,[]);
 await a.get('/api/knowledge/imports').query({limit:101}).expect(400);
 await request(app).get('/api/knowledge/imports').expect(401);
 await a.post('/api/knowledge/import-document').set('X-Gotek-Request','1').set('X-Gotek-Import-Id',pdf.requestId).attach('file',fixturePdf('Changed policy'),'policy.pdf').expect(409);
 assert.equal(pdf.state,'DRAFT');assert.equal(pdf.items[0].content,'Enterprise warranty 12 months');
 const storedPdf=(await a.get('/api/knowledge/items').expect(200)).body.items.find((item:any)=>item.id===pdf.items[0].id);
 assert.equal(storedPdf.content,'Enterprise warranty 12 months');
 assert.ok(!(await b.get('/api/knowledge/items').expect(200)).body.items.some((item:any)=>item.id===pdf.items[0].id));
 const same=(await send(a,'/api/knowledge/import',{items:[]}).expect(400)).body; assert.equal(same.error,'VALIDATION');
 assert.deepEqual((await a.get('/api/usage/ai').expect(200)).body,[]);
 await a.get('/api/usage/ai').query({from:'2026-09-26T00:00:00Z',to:'2026-09-25T00:00:00Z'}).expect(400);
 const before=(await a.get(`/api/knowledge/items?categoryId=${category.id}`)).body.items.length; await send(a,'/api/knowledge/import',{items:[{requestId:randomUUID(),title:'Batch good',content:'Good',categoryId:category.id},{requestId:randomUUID(),title:'',content:'Bad',categoryId:category.id}]}).expect(400); assert.equal((await a.get(`/api/knowledge/items?categoryId=${category.id}`)).body.items.length,before);
 await send(a,'/api/knowledge/import-file',{filename:'faq.json',content:'{broken'}).expect(400);
 await send(a,'/api/knowledge/import-file',{filename:'long.txt',content:'x'.repeat(2001)}).expect(400);
 await send(a,'/api/knowledge/import-file',{filename:'large.csv',content:'title,content\n'+'Question,Answer\n'.repeat(101)}).expect(400);
 const fileImport=(await send(a,'/api/knowledge/import-file',{filename:'faq.json',content:JSON.stringify([{title:'JSON FAQ',content:'JSON answer'}]),categoryId:category.id}).expect(200)).body; assert.equal(fileImport.imported,1); assert.equal(fileImport.state,'DRAFT');
 const bytes=(await a.post('/api/knowledge/import-bytes').set('X-Gotek-Request','1').set('Content-Type','text/plain').set('X-Gotek-Filename','notes.txt').send('Uploaded bytes').expect(200)).body; assert.equal(bytes.imported,1); assert.equal(bytes.state,'DRAFT');
 const quoted=(await send(a,'/api/knowledge/import-file',{filename:'quoted.csv',content:'title,content\n"FAQ, sản phẩm","Câu trả lời, có dấu phẩy"',categoryId:category.id}).expect(200)).body; assert.equal(quoted.imported,1);
 const processed=(await a.post(`/api/knowledge/items/${created.id}/process`).set('X-Gotek-Request','1').send({requestId:randomUUID(),expectedRevision:updated.revision,versionId:updated.draft_version_id}).expect(200)).body;
 const chunks=await a.get(`/api/knowledge/versions/${processed.versionId}/chunks`).query({query:'nội dung'}).expect(200); assert.ok(Array.isArray(chunks.body));
 await a.post('/api/knowledge/import-bytes').set('X-Gotek-Request','1').set('Content-Type','text/plain').send('Missing filename').expect(400);
 await send(a,'/api/knowledge/import-file',{filename:'faq.exe',content:'blocked',categoryId:category.id}).expect(415);
 await send(a,'/api/knowledge/import-file',{filename:'faq.csv',content:'wrong,columns\nonly-one',categoryId:category.id}).expect(400);
 await transaction(async db=>{await scope(db,me.workspaceId);await db.query("UPDATE memberships SET role='Agent' WHERE workspace_id=$1 AND user_id=$2",[me.workspaceId,me.user.id]);});
 await a.get('/api/knowledge-categories').expect(403);
 await a.get('/api/knowledge/imports').expect(403);
 await a.get('/api/knowledge/imports/'+document.importId+'/file').expect(403);
 await a.get('/api/usage/ai').expect(403);
 await a.post('/api/knowledge/import-document').set('X-Gotek-Request','1').attach('file',Buffer.from('invalid'),'invalid.docx').expect(403);
 await send(a,'/api/knowledge-categories',{requestId:randomUUID(),name:'Denied'}).expect(403);
 await a.get('/api/knowledge/items').expect(403);
 await send(a,'/api/knowledge/items',{...payload,requestId:randomUUID()}).expect(403);
 await a.patch(`/api/knowledge/items/${created.id}/draft`).set('X-Gotek-Request','1').send({...edit,requestId:randomUUID()}).expect(403);
});
