import {test,after} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID,createHmac} from 'node:crypto';
import pg from 'pg';
import request from 'supertest';
import {createApp} from '../src/app';
import {pool,transaction,scope} from '../src/core/db';
import {digest} from '../src/core/security';
import {enqueueFacebookReply,claimFacebookReply,completeFacebookReply} from '../src/modules/meta/outbox';
import {normalizeFacebookReceipt} from '../src/modules/meta/normalize';
const admin=new pg.Pool({host:process.env.PGHOST||'/tmp',port:Number(process.env.PGPORT)||55432,user:process.env.PGUSER||'gotek_migrator',password:process.env.PGPASSWORD||'gotek_dev_password',database:'gotek_chatbot'});
after(async()=>{await pool.end();await admin.end();});
test('Facebook HTTP callback consumes state once, hides tokens and rechecks revoked sessions',async()=>{
 const ws=randomUUID(),user=randomUUID(),token=randomUUID();
 const originalFetch=globalThis.fetch;
 const configured={META_FACEBOOK_VERIFY_TOKEN:'verify-fixture',META_FACEBOOK_APP_ID:'123',META_FACEBOOK_APP_SECRET:'fixture-secret',META_FACEBOOK_REDIRECT_URI:'https://example.test/api/integrations/meta/facebook/callback',META_FACEBOOK_LOGIN_CONFIG_ID:'456',META_GRAPH_VERSION:'v25.0',META_TOKEN_ENCRYPTION_KEY:'ab'.repeat(32)};
 const saved=Object.fromEntries(Object.keys(configured).map(k=>[k,process.env[k]]));
 Object.assign(process.env,configured);
 let calls=0, revoke=false;
 globalThis.fetch=async(input)=>{
  calls++;
  if(String(input).includes('/oauth/access_token')) {
   if(revoke)await admin.query('DELETE FROM sessions WHERE token_hash=$1',[digest(token)]);
   return Response.json({access_token:'private-user-token',expires_in:3600});
  }
  if(String(input).includes('/me/permissions'))return Response.json({data:['pages_show_list','pages_messaging','pages_manage_metadata','pages_read_engagement'].map(permission=>({permission,status:'granted'}))});
  if(String(input).includes('/subscribed_apps'))return Response.json({success:true});
  if(String(input).includes('/me/accounts'))return Response.json({data:[{id:'789',name:'Test Page',tasks:['MESSAGING'],access_token:'private-page-token'}]});
  throw new Error('Unexpected provider request');
 };
 const app=request(createApp()),base='/api/integrations/meta/facebook';
 const connect=()=>app.post(base+'/connect').set('Authorization','Bearer '+token).set('X-Gotek-Request','1');
 const callback=(state:string)=>app.get(base+'/callback').query({state,code:'fixture-code'}).set('Authorization','Bearer '+token);
 try {
  await admin.query("INSERT INTO users(id,email,full_name,phone,password_hash) VALUES($1,$2,'Meta fixture','','unused')",[user,user+'@example.test']);
  await admin.query("INSERT INTO workspaces(id,name) VALUES($1,'Meta fixture')",[ws]);
  await admin.query("INSERT INTO memberships(workspace_id,user_id,role) VALUES($1,$2,'Owner')",[ws,user]);
  await admin.query("INSERT INTO sessions(token_hash,user_id,workspace_id,expires_at) VALUES($1,$2,$3,now()+interval '1 hour')",[digest(token),user,ws]);
  const start=await connect();assert.equal(start.status,200);
  const state=new URL(start.body.authorizationUrl).searchParams.get('state')!;
  assert.equal((await callback('0'.repeat(64))).status,400);assert.equal(calls,0);
  const result=await callback(state);assert.equal(result.status,200);
  assert.equal(JSON.stringify(result.body).includes('private-'),false);
  assert.equal(result.headers['cache-control'],'no-store');
  assert.equal((await callback(state)).status,400);assert.equal(calls,2);
  const pages=await app.get(base+'/enrollments/'+result.body.enrollmentId+'/pages').set('Authorization','Bearer '+token);
  assert.equal(pages.status,200);assert.deepEqual(pages.body.assets,[{id:'789',name:'Test Page'}]);
  assert.equal(JSON.stringify(pages.body).includes('private-'),false);
  const selectionPath=base+'/enrollments/'+result.body.enrollmentId+'/select';
  assert.equal((await app.post(selectionPath).set('Authorization','Bearer '+token).set('X-Gotek-Request','1').send({assetId:'999'})).status,403);
  const selected=await app.post(selectionPath).set('Authorization','Bearer '+token).set('X-Gotek-Request','1').send({assetId:'789'});
  assert.equal(selected.status,201);assert.equal(selected.body.status,'pending');
  assert.equal((await app.post(selectionPath).set('Authorization','Bearer '+token).set('X-Gotek-Request','1').send({assetId:'789'})).status,400);
  const stored=(await admin.query('SELECT c.transport,c.enabled,m.token_ciphertext FROM channels c JOIN meta_connections m ON m.channel_id=c.id WHERE c.id=$1',[selected.body.channelId])).rows[0];
  assert.equal(stored.transport,'facebook');assert.equal(stored.enabled,false);assert.equal(stored.token_ciphertext.includes('private-page-token'),false);
  assert.equal((await app.get('/api/channels/'+selected.body.channelId+'/installation').set('Authorization','Bearer '+token)).status,409);
  const webhook='/integrations/meta/facebook/webhook';
  assert.equal((await app.get(webhook).query({'hub.mode':'subscribe','hub.verify_token':'wrong','hub.challenge':'challenge'})).status,403);
  const verified=await app.get(webhook).query({'hub.mode':'subscribe','hub.verify_token':'verify-fixture','hub.challenge':'challenge'});
  assert.equal(verified.status,200);assert.equal(verified.text,'challenge');
  const raw=JSON.stringify({object:'page',entry:[{id:'789',workspace_id:randomUUID(),messaging:[{timestamp:Date.now(),sender:{id:'111'},recipient:{id:'789'},message:{mid:'message-one',text:'hello'}}]}]});
  const signature='sha256='+createHmac('sha256','fixture-secret').update(raw).digest('hex');
  assert.equal((await app.post(webhook).set('Content-Type','application/json').send(raw)).status,403);
  assert.equal((await app.post(webhook).set('Content-Type','application/json').set('X-Hub-Signature-256',signature).send(raw+' ')).status,403);
  for(let i=0;i<2;i++)assert.equal((await app.post(webhook).set('Content-Type','application/json').set('X-Hub-Signature-256',signature).send(raw)).status,200);
  const receipts=await admin.query('SELECT * FROM meta_webhook_receipts WHERE workspace_id=$1',[ws]);
  assert.equal(receipts.rowCount,1);assert.equal(receipts.rows[0].connection_id,selected.body.id);
  await admin.query("UPDATE workspaces SET status='disabled' WHERE id=$1",[ws]);
  const blockedRaw=raw.replace('message-one','message-two');
  const blockedSignature='sha256='+createHmac('sha256','fixture-secret').update(blockedRaw).digest('hex');
  assert.equal((await app.post(webhook).set('Content-Type','application/json').set('X-Hub-Signature-256',blockedSignature).send(blockedRaw)).status,200);
  assert.equal((await admin.query('SELECT id FROM meta_webhook_receipts WHERE workspace_id=$1',[ws])).rowCount,1);
  await admin.query("UPDATE workspaces SET status='active' WHERE id=$1",[ws]);
  const normalize=()=>transaction(async db=>{await scope(db,ws);return normalizeFacebookReceipt(db,ws);});
  assert.equal((await normalize()).state,'waiting_connection');
  // Provider subscription is mocked; exercise the authenticated activation endpoint.
  assert.equal((await app.post(base+'/connections/'+selected.body.id+'/activate').set('Authorization','Bearer '+token).set('X-Gotek-Request','1')).status,200);
  assert.equal((await normalize()).inserted,1);
  assert.equal((await normalize()).state,'idle');
  const repeated=JSON.stringify({...JSON.parse(raw),entry:JSON.parse(raw).entry.map((entry:any)=>({...entry,time:12345}))});
  const repeatedSignature='sha256='+createHmac('sha256','fixture-secret').update(repeated).digest('hex');
  assert.equal((await app.post(webhook).set('Content-Type','application/json').set('X-Hub-Signature-256',repeatedSignature).send(repeated)).status,200);
  assert.equal((await normalize()).duplicates,1);
  assert.equal((await admin.query('SELECT id FROM messages WHERE workspace_id=$1',[ws])).rowCount,1);
  const inbox=await app.get('/api/conversations').set('Authorization','Bearer '+token);
  assert.equal(inbox.status,200);
  const conversation=(await admin.query('SELECT id FROM conversations WHERE workspace_id=$1',[ws])).rows[0];
  assert.ok(conversation);
  assert.ok(inbox.body.some((item:any)=>item.id===conversation.id));
  const messages=await app.get('/api/conversations/'+conversation.id+'/messages').set('Authorization','Bearer '+token);
  assert.equal(messages.status,200);assert.equal(messages.body[0].body,'hello');
  const sendPath='/api/conversations/'+conversation.id+'/messages';
  const send=await app.post(sendPath).set('Authorization','Bearer '+token).set('X-Gotek-Request','1').send({clientId:randomUUID(),body:'not actually sent',visibility:'public'});
  assert.equal(send.status,409);assert.equal(send.body.error,'TAKEOVER_REQUIRED');
  const note=await app.post(sendPath).set('Authorization','Bearer '+token).set('X-Gotek-Request','1').send({clientId:randomUUID(),body:'internal note',visibility:'internal'});
  assert.equal(note.status,200);
  const resume=await app.post('/api/conversations/'+conversation.id+'/resume-ai').set('Authorization','Bearer '+token).set('X-Gotek-Request','1').send({version:1});
  assert.equal(resume.status,409);assert.equal(resume.body.error,'META_OUTBOUND_NOT_READY');
  assert.equal((await admin.query("SELECT id FROM messages WHERE workspace_id=$1 AND author_type='agent' AND visibility='public'",[ws])).rowCount,0);
  const enqueue=(clientId:string,text='queued reply')=>transaction(async db=>{await scope(db,ws);return enqueueFacebookReply(db,{workspace_id:ws,user_id:user,role:'Owner'},conversation.id,{clientId,body:text});});
  await assert.rejects(enqueue(randomUUID()),/TAKEOVER_REQUIRED/);
  await admin.query("UPDATE conversations SET reply_owner='HUMAN_ACTIVE',assigned_to=$1,owner_version=owner_version+1 WHERE id=$2",[user,conversation.id]);
  const clientId=randomUUID();
  const queuedResponse=await app.post(sendPath).set('Authorization','Bearer '+token).set('X-Gotek-Request','1').send({clientId,body:'queued reply',visibility:'public'});
  assert.equal(queuedResponse.status,200);
  const queued=queuedResponse.body;assert.equal(queued.delivery_status,'queued');
  assert.equal((await enqueue(clientId)).id,queued.id);
  await assert.rejects(enqueue(clientId,'different'),/IDEMPOTENCY_CONFLICT/);
  assert.equal((await admin.query('SELECT id FROM meta_outbox WHERE workspace_id=$1',[ws])).rowCount,1);
  await admin.query("UPDATE meta_contacts SET last_inbound_at=now()-interval '25 hours' WHERE workspace_id=$1",[ws]);
  await assert.rejects(enqueue(randomUUID()),/META_MESSAGING_WINDOW_CLOSED/);
  const claim=()=>transaction(async db=>{await scope(db,ws);return claimFacebookReply(db,ws);});
  assert.equal((await claim())?.state,'cancelled');
  await admin.query('UPDATE meta_contacts SET last_inbound_at=now() WHERE workspace_id=$1',[ws]);
  await enqueue(randomUUID());
  const claims=await Promise.all([claim(),claim()]);
  assert.equal(claims.filter(item=>item?.state==='dispatching').length,1);
  assert.equal(claims.filter(item=>item===null).length,1);
  assert.equal(await claim(),null);
  assert.equal((await admin.query("SELECT id FROM meta_outbox WHERE workspace_id=$1 AND status='dispatching'",[ws])).rowCount,1);
  const dispatched=claims.find(item=>item?.state==='dispatching')!;
  const complete=(id:string,result:{status:'accepted';messageId:string}|{status:'unknown'})=>transaction(async db=>{await scope(db,ws);return completeFacebookReply(db,ws,id,result);});
  assert.equal((await complete(dispatched.id,{status:'accepted',messageId:'provider-receipt-one'})).status,'accepted');
  await assert.rejects(complete(dispatched.id,{status:'unknown'}),/META_OUTBOX_STATE_INVALID/);
  const acceptedMessages=await app.get(sendPath).set('Authorization','Bearer '+token);
  assert.equal(acceptedMessages.status,200);
  const acceptedMessage=acceptedMessages.body.find((m:any)=>m.provider_message_id==='provider-receipt-one');
  assert.equal(acceptedMessage.delivery_status,'accepted');
  await enqueue(randomUUID());
  const uncertain=await claim();assert.equal(uncertain?.state,'dispatching');
  assert.equal((await complete(uncertain!.id,{status:'unknown'})).status,'unknown');
  assert.equal(await claim(),null); // Unknown outcomes must never be automatically resent.
  const unknownMessages=await app.get(sendPath).set('Authorization','Bearer '+token);
  assert.ok(unknownMessages.body.some((m:any)=>m.delivery_status==='unknown'&&m.provider_message_id===null));
  // A lost HTTP acknowledgement remains recoverable after ownership changes, without a new send.
  await admin.query("UPDATE conversations SET assigned_to=NULL,owner_version=owner_version+1 WHERE id=$1",[conversation.id]);
  assert.equal((await enqueue(clientId)).id,queued.id);
  await assert.rejects(enqueue(randomUUID()),/TAKEOVER_REQUIRED/);
  await admin.query('UPDATE conversations SET assigned_to=$1 WHERE id=$2',[user,conversation.id]);
  // A queued reply must be cancelled if the actor loses membership before dispatch.
  await enqueue(randomUUID());
  await admin.query('UPDATE memberships SET active=false WHERE workspace_id=$1 AND user_id=$2',[ws,user]);
  assert.equal((await claim())?.state,'cancelled');
  await admin.query('UPDATE memberships SET active=true WHERE workspace_id=$1 AND user_id=$2',[ws,user]);
  // A reconnect generation invalidates already queued work.
  await enqueue(randomUUID());
  await admin.query('UPDATE meta_connections SET generation=generation+1 WHERE id=$1',[selected.body.id]);
  assert.equal((await claim())?.state,'cancelled');
  // Ownership changing while queued also fences dispatch.
  await enqueue(randomUUID());
  await admin.query('UPDATE conversations SET owner_version=owner_version+1 WHERE id=$1',[conversation.id]);
  assert.equal((await claim())?.state,'cancelled');
  assert.equal(await claim(),null);
  const deniedState=new URL((await connect()).body.authorizationUrl).searchParams.get('state')!;
  assert.equal((await app.get(base+'/callback').query({state:deniedState,error:'access_denied'}).set('Authorization','Bearer '+token)).status,400);
  const before=calls;assert.equal((await callback(deniedState)).status,400);assert.equal(calls,before);
  const revokedState=new URL((await connect()).body.authorizationUrl).searchParams.get('state')!;
  revoke=true;assert.equal((await callback(revokedState)).status,401);
  assert.equal((await admin.query('SELECT id FROM meta_enrollments WHERE workspace_id=$1',[ws])).rowCount,0);
 } finally {
  globalThis.fetch=originalFetch;
  for(const [k,v] of Object.entries(saved)){if(v===undefined)delete process.env[k];else process.env[k]=v;}
  for(const table of ['meta_outbox','meta_inbound_messages','meta_contacts','messages','conversations','visitors','meta_webhook_receipts','meta_connections','channel_members','channels','audit_events'])await admin.query(`DELETE FROM ${table} WHERE workspace_id=$1`,[ws]);
  for(const table of ['meta_enrollments','meta_oauth_attempts','sessions','memberships'])await admin.query(`DELETE FROM ${table} WHERE workspace_id=$1`,[ws]);
  await admin.query('DELETE FROM workspaces WHERE id=$1',[ws]);
  await admin.query('DELETE FROM users WHERE id=$1',[user]);
 }
});
