import {ChannelConfiguration} from './ChannelConfiguration';
import {useEffect,useState,type FormEvent} from 'react';import {api} from './api';
export function Channels({role}:{role:string}){
 const[rows,setRows]=useState<any[]>([]),[members,setMembers]=useState<any[]>([]),[step,setStep]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState(''),[install,setInstall]=useState<any>(null),[settings,setSettings]=useState<any>(null);
 const[input,setInput]=useState({requestId:crypto.randomUUID(),name:'',origin:'',greeting:'Xin chào! Chúng tôi có thể giúp gì cho bạn?',color:'#0057E1',agents:[] as string[]});const canManage=['Owner','Admin'].includes(role);
 async function load(){setRows(await api('/channels'));if(canManage)setMembers((await api('/members')).filter((m:any)=>m.active));}
 async function showInstall(id:string){setError('');try{setInstall(await api(`/channels/${id}/installation`));}catch(e){setError((e as Error).message);}}
 async function toggleChannel(id:string,enabled:boolean){setError('');try{await api(`/channels/${id}/state`,'PATCH',{enabled});await load();}catch(e){setError((e as Error).message);}}
 async function showSettings(id:string){setError('');try{setSettings(await api(`/channels/${id}/settings`));}catch(e){setError((e as Error).message);}}
 async function saveSettings(){if(!settings)return;setBusy(true);try{await api(`/channels/${settings.id}/settings`,'PATCH',{assignmentEnabled:settings.assignment_enabled,assignmentLimit:settings.assignment_limit,businessHours:settings.business_hours,prechat:settings.prechat});setSettings(await api(`/channels/${settings.id}/settings`));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 useEffect(()=>{load().catch(e=>setError(e.message));},[]);
 async function submit(e:FormEvent){e.preventDefault();setError('');if(step<3){setStep(step+1);return;}setBusy(true);try{const result=await api('/channels','POST',input);setSaved(result.id);await showInstall(result.id);setStep(4);await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <><h1>Hộp thư</h1>{error&&<div role="alert" className="notice error">{error}</div>}<button onClick={()=>load().catch(e=>setError(e.message))}>Làm mới</button>{canManage&&step===0&&<button className="primary" onClick={()=>{setSaved('');setInput({requestId:crypto.randomUUID(),name:'',origin:'',greeting:'Xin chào! Chúng tôi có thể giúp gì cho bạn?',color:'#0057E1',agents:[]});setStep(1);}}>Kênh mới</button>}
 {step>0&&<section className="panel"><h2>Tạo kênh website</h2><p>Bước {Math.min(step,4)}/4 · {['','Chọn loại kênh','Thông tin website','Cộng tác viên','Hoàn tất'][step]}</p>{step===4?<><p role="status">Đã tạo và lưu kênh website.</p><code>{saved}</code><p>Mã nhúng đã sẵn sàng cho website đã đăng ký.</p><button onClick={()=>setStep(0)}>Về danh sách</button></>:<form onSubmit={submit}><fieldset disabled={busy}>{step===1?<label><input type="radio" checked readOnly/> Website</label>:step===2?<>{(['name','origin','greeting'] as const).map((key,i)=><label className="field" key={key}>{['Tên website','Domain website','Lời chào'][i]}<input required type={key==='origin'?'url':'text'} maxLength={key==='name'?100:500} value={input[key]} onChange={e=>setInput({...input,[key]:e.target.value})}/></label>)}<label className="field">Màu chủ đề<input type="color" value={input.color} onChange={e=>setInput({...input,color:e.target.value})}/></label></>:<><p>Chọn cộng tác viên tham gia hộp thư.</p>{members.map(m=><label className="field" key={m.id}><span><input type="checkbox" checked={input.agents.includes(m.id)} onChange={e=>setInput({...input,agents:e.target.checked?[...input.agents,m.id]:input.agents.filter(id=>id!==m.id)})}/>{m.full_name} · {m.role}</span></label>)}</>}
 <div style={{display:'flex',gap:12,marginTop:24}}><button type="button" onClick={()=>setStep(step-1)}>Quay lại</button><button className="primary" disabled={busy||step===3&&!input.agents.length}>{busy?'Đang lưu…':step===3?'Tạo kênh':'Tiếp tục'}</button></div></fieldset></form>}</section>}
 {!rows.length?<p className="empty">Chưa có hộp thư khả dụng.</p>:<div className="table-wrap"><table><thead><tr><th>Tên</th><th>Website</th><th>Trạng thái</th><th></th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.name}</td><td>{r.origin}</td><td>{r.enabled?'Hoạt động':'Tắt'}</td><td>{canManage&&<button onClick={()=>toggleChannel(r.id,!r.enabled)}>{r.enabled?'Tắt kênh':'Bật kênh'}</button>} {canManage&&<><button onClick={()=>showInstall(r.id)}>Mã nhúng</button> <button onClick={()=>showSettings(r.id)}>Cấu hình</button></>}</td></tr>)}</tbody></table></div>}{install&&<section className="panel"><h2>Mã nhúng: {install.name}</h2><p>Chỉ dùng trên đúng origin <code>{install.origin}</code>.</p><textarea aria-label="Mã nhúng" readOnly rows={5} value={install.snippet}/><button onClick={()=>setInstall(null)}>Đóng</button></section>}{settings&&<ChannelConfiguration key={settings.id} initial={settings} onClose={()=>setSettings(null)}/>}</>;
}
