import type {PoolClient} from 'pg';
import {randomUUID} from 'node:crypto';
import {z} from 'zod';
import {HttpError,requireRole,audit} from '../../core/security';
const bodySchema=z.object({requestId:z.string().uuid(),groupId:z.string().uuid(),snapshotId:z.string().uuid(),parts:z.array(z.object({partIndex:z.number().int().nonnegative(),action:z.enum(['UPSERT','RETIRE']),itemId:z.string().uuid().nullable().optional(),versionId:z.string().uuid().nullable().optional()})).min(1).max(100)}).strict();
export async function createWebGeneration(db:PoolClient,actor:any,body:unknown){
 requireRole(actor.role);const data=bodySchema.parse(body);const normalized={...data,parts:[...data.parts].sort((a,b)=>a.partIndex-b.partIndex)};
 if(new Set(normalized.parts.map(x=>x.partIndex)).size!==normalized.parts.length)throw new HttpError(409,'DUPLICATE_PART_INDEX');
 await db.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[`web-generation-request:${actor.workspace_id}:${data.requestId}`]);
 await db.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[`web-generation:${actor.workspace_id}:${data.groupId}`]);
 const old=(await db.query('SELECT id,state,group_id,snapshot_id FROM web_source_generations WHERE workspace_id=$1 AND request_id=$2',[actor.workspace_id,data.requestId])).rows[0];if(old){if(old.group_id!==data.groupId||old.snapshot_id!==data.snapshotId)throw new HttpError(409,'IDEMPOTENCY_CONFLICT');const saved=(await db.query('SELECT part_index,action,knowledge_item_id,version_id FROM web_source_generation_parts WHERE workspace_id=$1 AND generation_id=$2 ORDER BY part_index',[actor.workspace_id,old.id])).rows;const requested=normalized.parts.map(p=>({part_index:p.partIndex,action:p.action,knowledge_item_id:p.itemId??null,version_id:p.versionId??null}));if(JSON.stringify(saved)!==JSON.stringify(requested))throw new HttpError(409,'IDEMPOTENCY_CONFLICT');return {generationId:old.id,state:old.state,replayed:true};}
 const group=(await db.query('SELECT id,current_generation_id,published_generation_id FROM web_source_document_groups WHERE workspace_id=$1 AND id=$2 FOR UPDATE',[actor.workspace_id,data.groupId])).rows[0];if(!group)throw new HttpError(404,'NOT_FOUND');if(group.current_generation_id){const state=(await db.query('SELECT state FROM web_source_generations WHERE workspace_id=$1 AND id=$2',[actor.workspace_id,group.current_generation_id])).rows[0]?.state;if(state==='DRAFT')throw new HttpError(409,'DRAFT_EXISTS');}
 const snapshot=(await db.query('SELECT id,source_id FROM web_source_snapshots WHERE workspace_id=$1 AND id=$2',[actor.workspace_id,data.snapshotId])).rows[0];if(!snapshot)throw new HttpError(404,'NOT_FOUND');if(snapshot.source_id!== (await db.query('SELECT source_id FROM web_source_document_groups WHERE workspace_id=$1 AND id=$2',[actor.workspace_id,data.groupId])).rows[0].source_id)throw new HttpError(409,'SOURCE_MISMATCH');
 for(const part of normalized.parts){if(part.action==='RETIRE'){if(part.itemId!==undefined&&part.itemId!==null)throw new HttpError(400,'RETIRE_ITEM_NOT_ALLOWED');continue;}if(!part.itemId||!part.versionId)throw new HttpError(400,'UPSERT_VERSION_REQUIRED');const v=(await db.query('SELECT id FROM knowledge_versions WHERE workspace_id=$1 AND item_id=$2 AND id=$3',[actor.workspace_id,part.itemId,part.versionId])).rows[0];if(!v)throw new HttpError(409,'VERSION_CONFLICT');}
 const parent=group.published_generation_id;
 const id=randomUUID();await db.query('INSERT INTO web_source_generations(id,workspace_id,group_id,snapshot_id,parent_generation_id,request_id) VALUES($1,$2,$3,$4,$5,$6)',[id,actor.workspace_id,data.groupId,data.snapshotId,parent,data.requestId]);
 for(const p of normalized.parts)await db.query('INSERT INTO web_source_generation_parts(workspace_id,generation_id,part_index,action,knowledge_item_id,version_id) VALUES($1,$2,$3,$4,$5,$6)',[actor.workspace_id,id,p.partIndex,p.action,p.itemId??null,p.versionId??null]);
 await db.query('UPDATE web_source_document_groups SET current_generation_id=$1 WHERE workspace_id=$2 AND id=$3',[id,actor.workspace_id,data.groupId]);await audit(db,actor.workspace_id,actor.user_id,'web_source.generation_created',id);
 return {generationId:id,state:'DRAFT',replayed:false};
}

export async function publishWebGeneration(db:PoolClient,actor:any,generationId:string,body:unknown){
 requireRole(actor.role);const data=z.object({requestId:z.string().uuid(),expectedParentId:z.string().uuid().nullable().optional()}).strict().parse(body);z.string().uuid().parse(generationId);
 await db.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[`web-generation-publish:${actor.workspace_id}:${generationId}`]);
 await db.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[`knowledge:${actor.workspace_id}:${data.requestId}`]);
 const old=(await db.query('SELECT operation,payload=$3::jsonb AS same,response FROM knowledge_mutations WHERE workspace_id=$1 AND request_id=$2',[actor.workspace_id,data.requestId,{generationId,expectedParentId:data.expectedParentId??null}])).rows[0];if(old){if(old.operation!=='web_source.generation_published'||!old.same)throw new HttpError(409,'IDEMPOTENCY_CONFLICT');return old.response;}
 const gen=(await db.query('SELECT g.*,d.published_generation_id FROM web_source_generations g JOIN web_source_document_groups d ON d.workspace_id=g.workspace_id AND d.id=g.group_id WHERE g.workspace_id=$1 AND g.id=$2 FOR UPDATE',[actor.workspace_id,generationId])).rows[0];if(!gen)throw new HttpError(404,'NOT_FOUND');
 await db.query('SELECT id FROM web_source_document_groups WHERE workspace_id=$1 AND id=$2 FOR UPDATE',[actor.workspace_id,gen.group_id]);
 if(gen.state!=='DRAFT')throw new HttpError(409,'INVALID_STATE');if(gen.published_generation_id!==gen.parent_generation_id)throw new HttpError(409,'VERSION_CONFLICT');if(data.expectedParentId!==undefined&&data.expectedParentId!==gen.parent_generation_id)throw new HttpError(409,'VERSION_CONFLICT');
 const parts=(await db.query('SELECT * FROM web_source_generation_parts WHERE workspace_id=$1 AND generation_id=$2 ORDER BY part_index',[actor.workspace_id,generationId])).rows;
 if(!parts.length||parts.some((p:any,i:number)=>p.part_index!==i))throw new HttpError(409,'GENERATION_MANIFEST_INCOMPLETE');
 if(gen.parent_generation_id){const prior=(await db.query('SELECT part_index,action FROM web_source_generation_parts WHERE workspace_id=$1 AND generation_id=$2',[actor.workspace_id,gen.parent_generation_id])).rows;if(prior.some((p:any)=>p.action==='UPSERT'&&!parts.some((next:any)=>next.part_index===p.part_index)))throw new HttpError(409,'GENERATION_MANIFEST_INCOMPLETE');}
 for(const p of parts){if(p.action==='UPSERT'){const v=(await db.query("SELECT state FROM knowledge_versions WHERE workspace_id=$1 AND item_id=$2 AND id=$3 FOR UPDATE",[actor.workspace_id,p.knowledge_item_id,p.version_id])).rows[0];if(!v)throw new HttpError(404,'NOT_FOUND');if(v.state!=='READY')throw new HttpError(409,'GENERATION_NOT_READY');}}
 const selectedIds=parts.filter((p:any)=>p.action==='UPSERT').map((p:any)=>p.knowledge_item_id);
 if(gen.parent_generation_id){const previous=(await db.query("SELECT knowledge_item_id FROM web_source_generation_parts WHERE workspace_id=$1 AND generation_id=$2 AND action='UPSERT'",[actor.workspace_id,gen.parent_generation_id])).rows;for(const p of previous){if(!selectedIds.includes(p.knowledge_item_id))await db.query('UPDATE knowledge_items SET active=false,revision=revision+1,updated_at=now() WHERE workspace_id=$1 AND id=$2',[actor.workspace_id,p.knowledge_item_id]);}}
 for(const p of parts){if(p.action==='UPSERT')await db.query('UPDATE knowledge_items SET active=true,published_version_id=$1,audience=\'PUBLIC\',revision=revision+1,updated_at=now() WHERE workspace_id=$2 AND id=$3',[p.version_id,actor.workspace_id,p.knowledge_item_id]);}
 for(const p of parts){if(p.action==='UPSERT'){
  await db.query('UPDATE knowledge_versions SET first_published_at=coalesce(first_published_at,now()) WHERE workspace_id=$1 AND id=$2',[actor.workspace_id,p.version_id]);
  await db.query('UPDATE knowledge_items SET published_at=now(),published_by=$3 WHERE workspace_id=$1 AND id=$2',[actor.workspace_id,p.knowledge_item_id,actor.user_id]);
 }}
 await db.query("UPDATE web_source_generations SET state='PUBLISHED' WHERE workspace_id=$1 AND id=$2",[actor.workspace_id,generationId]);await db.query('UPDATE web_source_document_groups SET published_generation_id=$1,current_generation_id=$1 WHERE workspace_id=$2 AND id=$3',[generationId,actor.workspace_id,gen.group_id]);const response={generationId,state:'PUBLISHED'};await audit(db,actor.workspace_id,actor.user_id,'web_source.generation_published',generationId);await db.query('INSERT INTO knowledge_mutations(workspace_id,request_id,operation,payload,response) VALUES($1,$2,$3,$4,$5)',[actor.workspace_id,data.requestId,'web_source.generation_published',{generationId,expectedParentId:data.expectedParentId??null},response]);return response;
}

export async function rollbackWebGeneration(db:PoolClient,actor:any,generationId:string,body:unknown){
 requireRole(actor.role);const data=z.object({requestId:z.string().uuid()}).strict().parse(body);z.string().uuid().parse(generationId);
 await db.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[`web-generation-publish:${actor.workspace_id}:${generationId}`]);
 await db.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[`knowledge:${actor.workspace_id}:${data.requestId}`]);
 const old=(await db.query('SELECT operation,payload=$3::jsonb AS same,response FROM knowledge_mutations WHERE workspace_id=$1 AND request_id=$2',[actor.workspace_id,data.requestId,{generationId}])).rows[0];if(old){if(old.operation!=='web_source.generation_rolled_back'||!old.same)throw new HttpError(409,'IDEMPOTENCY_CONFLICT');return old.response;}
 const gen=(await db.query('SELECT g.*,d.published_generation_id FROM web_source_generations g JOIN web_source_document_groups d ON d.workspace_id=g.workspace_id AND d.id=g.group_id WHERE g.workspace_id=$1 AND g.id=$2 FOR UPDATE',[actor.workspace_id,generationId])).rows[0];if(!gen)throw new HttpError(404,'NOT_FOUND');
 await db.query('SELECT id FROM web_source_document_groups WHERE workspace_id=$1 AND id=$2 FOR UPDATE',[actor.workspace_id,gen.group_id]);
 if(gen.published_generation_id!==generationId)throw new HttpError(409,'VERSION_CONFLICT');
 if(gen.state!=='PUBLISHED'||!gen.parent_generation_id)throw new HttpError(409,'ROLLBACK_UNAVAILABLE');
 const parent=(await db.query("SELECT id,state FROM web_source_generations WHERE workspace_id=$1 AND id=$2 FOR UPDATE",[actor.workspace_id,gen.parent_generation_id])).rows[0];if(!parent)throw new HttpError(409,'ROLLBACK_UNAVAILABLE');
 const current=(await db.query("SELECT part_index,knowledge_item_id,version_id,action FROM web_source_generation_parts WHERE workspace_id=$1 AND generation_id=$2",[actor.workspace_id,generationId])).rows;
 const prior=(await db.query("SELECT part_index,knowledge_item_id,version_id,action FROM web_source_generation_parts WHERE workspace_id=$1 AND generation_id=$2",[actor.workspace_id,gen.parent_generation_id])).rows;
 const priorItemIds=new Set(prior.filter((p:any)=>p.action==='UPSERT').map((p:any)=>p.knowledge_item_id));
 for(const p of current){if(p.action==='UPSERT'&&!priorItemIds.has(p.knowledge_item_id))await db.query('UPDATE knowledge_items SET active=false,revision=revision+1,updated_at=now() WHERE workspace_id=$1 AND id=$2',[actor.workspace_id,p.knowledge_item_id]);}
 for(const p of prior){if(p.action==='UPSERT')await db.query('UPDATE knowledge_items SET active=true,published_version_id=$1,revision=revision+1,updated_at=now() WHERE workspace_id=$2 AND id=$3',[p.version_id,actor.workspace_id,p.knowledge_item_id]);}
 await db.query("UPDATE web_source_generations SET state='ROLLED_BACK' WHERE workspace_id=$1 AND id=$2",[actor.workspace_id,generationId]);await db.query("UPDATE web_source_generations SET state='PUBLISHED' WHERE workspace_id=$1 AND id=$2",[actor.workspace_id,gen.parent_generation_id]);await db.query('UPDATE web_source_document_groups SET current_generation_id=$1,published_generation_id=$1 WHERE workspace_id=$2 AND id=$3',[gen.parent_generation_id,actor.workspace_id,gen.group_id]);const response={generationId,state:'ROLLED_BACK',restoredGenerationId:gen.parent_generation_id};await audit(db,actor.workspace_id,actor.user_id,'web_source.generation_rolled_back',generationId);await db.query('INSERT INTO knowledge_mutations(workspace_id,request_id,operation,payload,response) VALUES($1,$2,$3,$4,$5)',[actor.workspace_id,data.requestId,'web_source.generation_rolled_back',{generationId},response]);return response;
}
