import type {PoolClient} from 'pg';import {z} from 'zod';import {uuid,HttpError} from '../../core/security';
export async function appendMessage(db:PoolClient,input:{workspace:string,conversation:string,clientId:string,author:'visitor'|'agent'|'ai',actor?:string,visibility:'public'|'internal',body:string,ownerVersion?:number}){
 z.string().uuid().parse(input.clientId);z.string().min(1).max(10000).parse(input.body);
 if(input.visibility==='internal'&&input.author!=='agent')throw new HttpError(403,'INVALID_VISIBILITY');
 const c=(await db.query('SELECT * FROM conversations WHERE id=$1 AND workspace_id=$2 FOR UPDATE',[input.conversation,input.workspace])).rows[0];if(!c)throw new HttpError(404,'NOT_FOUND');
 const old=(await db.query('SELECT * FROM messages WHERE conversation_id=$1 AND client_id=$2',[c.id,input.clientId])).rows[0];if(old){if(old.body!==input.body||old.author_type!==input.author||old.visibility!==input.visibility||old.actor_id!==(input.actor??null))throw new HttpError(409,'IDEMPOTENCY_CONFLICT');return old;}
 if(input.author==='ai'&&(c.reply_owner!=='AI_ACTIVE'||c.owner_version!==input.ownerVersion))throw new HttpError(409,'STALE_REPLY_OWNER');
 if(input.author==='agent'&&input.visibility==='public'&&(c.reply_owner!=='HUMAN_ACTIVE'||c.assigned_to!==input.actor))throw new HttpError(409,'TAKEOVER_REQUIRED');
 const message=(await db.query('INSERT INTO messages(id,workspace_id,conversation_id,client_id,sequence,author_type,actor_id,visibility,body) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *',[uuid(),input.workspace,c.id,input.clientId,c.next_sequence,input.author,input.actor??null,input.visibility,input.body])).rows[0];await db.query("UPDATE conversations SET next_sequence=next_sequence+1,updated_at=now(),status=CASE WHEN $2='visitor' THEN 'open' ELSE status END WHERE id=$1",[c.id,input.author]);return message;
}
export async function takeover(db:PoolClient,workspace:string,conversation:string,actor:string,version:number){const row=(await db.query("UPDATE conversations SET reply_owner='HUMAN_ACTIVE',assigned_to=$1,owner_version=owner_version+1,updated_at=now() WHERE workspace_id=$2 AND id=$3 AND owner_version=$4 RETURNING id,owner_version,assigned_to",[actor,workspace,conversation,version])).rows[0];if(!row)throw new HttpError(409,'STALE_REPLY_OWNER');return row;}
