import type {PoolClient} from 'pg';import {z} from 'zod';import {HttpError,audit,requireRole,uuid} from '../../core/security';
const schema=z.object({requestId:z.string().uuid(),fullName:z.string().trim().min(1).max(200),email:z.string().trim().email().max(320).nullable().optional(),phone:z.string().trim().min(3).max(40).nullable().optional(),country:z.string().trim().min(2).max(100).nullable().optional(),city:z.string().trim().min(2).max(100).nullable().optional(),bio:z.string().trim().max(5000).nullable().optional(),company:z.string().trim().min(1).max(200).nullable().optional(),notes:z.string().trim().max(200).nullable().optional()}).strict();
export async function createContact(db:PoolClient,actor:any,body:unknown){requireRole(actor.role);const d=schema.parse(body);await db.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[`knowledge:${actor.workspace_id}:${d.requestId}`]);const old=(await db.query('SELECT operation,payload=$3::jsonb AS same,response FROM knowledge_mutations WHERE workspace_id=$1 AND request_id=$2',[actor.workspace_id,d.requestId,d])).rows[0];if(old){if(old.operation!=='contact.created'||!old.same)throw new HttpError(409,'IDEMPOTENCY_CONFLICT');return old.response;}const id=uuid();const row=(await db.query('INSERT INTO contacts(id,workspace_id,full_name,email,phone,country,city,bio,company,notes,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING id,full_name,email,phone,country,city,bio,company,notes,revision,created_at,updated_at',[id,actor.workspace_id,d.fullName,d.email??null,d.phone??null,d.country??null,d.city??null,d.bio??null,d.company??null,d.notes??null,actor.user_id])).rows[0];await audit(db,actor.workspace_id,actor.user_id,'contact.created',id);await db.query('INSERT INTO knowledge_mutations(workspace_id,request_id,operation,payload,response) VALUES($1,$2,$3,$4,$5)',[actor.workspace_id,d.requestId,'contact.created',d,row]);return row;}
export async function listContacts(db:PoolClient,actor:any,query:unknown){requireRole(actor.role,['Owner','Admin']);const q=z.object({search:z.string().trim().max(200).optional(),tag:z.string().trim().max(80).optional(),limit:z.coerce.number().int().min(1).max(100).default(25),cursor:z.string().uuid().optional()}).strict().parse(query);const p:any[]=[actor.workspace_id],w=['workspace_id=$1'];if(q.search){p.push(`%${q.search.replace(/[\\%_]/g,'\\$&')}%`);w.push(`(full_name ILIKE $${p.length} OR email ILIKE $${p.length} OR phone ILIKE $${p.length} OR country ILIKE $${p.length} OR city ILIKE $${p.length} OR company ILIKE $${p.length} OR bio ILIKE $${p.length} OR notes ILIKE $${p.length})`);}if(q.tag){p.push(q.tag);w.push(`EXISTS (SELECT 1 FROM contact_tag_links l JOIN contact_tags t ON t.id=l.tag_id AND t.workspace_id=l.workspace_id WHERE l.workspace_id=$1 AND l.contact_id=contacts.id AND t.name=$${p.length})`);}if(q.cursor){const anchor=(await db.query('SELECT id FROM contacts WHERE workspace_id=$1 AND id=$2 AND deleted_at IS NULL',[actor.workspace_id,q.cursor])).rows[0];if(!anchor)throw new HttpError(400,'INVALID_CURSOR');p.push(q.cursor);w.push(`(created_at,id)<(SELECT created_at,id FROM contacts WHERE workspace_id=$1 AND id=$${p.length} AND deleted_at IS NULL)`);}p.push(q.limit+1);const rows=(await db.query(`SELECT id,full_name,email,phone,country,city,bio,company,notes,revision,created_at,updated_at FROM contacts WHERE deleted_at IS NULL AND ${w.join(' AND ')} ORDER BY created_at DESC,id DESC LIMIT $${p.length}`,p)).rows;const items=rows.slice(0,q.limit);
 const tagsByContact=new Map<string,Array<{id:string,name:string,color:string|null}>>();
 if(items.length){
  const links=(await db.query('SELECT l.contact_id,t.id,t.name,t.color FROM contact_tag_links l JOIN contact_tags t ON t.workspace_id=l.workspace_id AND t.id=l.tag_id WHERE l.workspace_id=$1 AND l.contact_id=ANY($2::uuid[]) ORDER BY t.name,t.id',[actor.workspace_id,items.map(item=>item.id)])).rows;
  for(const {contact_id,...tag} of links){const tags=tagsByContact.get(contact_id)??[];tags.push(tag);tagsByContact.set(contact_id,tags);}
 }
 return {items:items.map(item=>({...item,tags:tagsByContact.get(item.id)??[]})),nextCursor:rows.length>q.limit?rows[q.limit-1].id:null};}

export async function exportContacts(db:PoolClient,actor:any,query:unknown){
 requireRole(actor.role,['Owner','Admin']);const q=z.object({search:z.string().trim().max(200).optional(),tag:z.string().trim().min(1).max(80).optional()}).strict().parse(query);const p:any[]=[actor.workspace_id],w=['workspace_id=$1','deleted_at IS NULL'];
 if(q.search){p.push(`%${q.search.replace(/[\\%_]/g,'\\$&')}%`);w.push(`(full_name ILIKE $${p.length} OR email ILIKE $${p.length} OR phone ILIKE $${p.length} OR country ILIKE $${p.length} OR city ILIKE $${p.length} OR company ILIKE $${p.length} OR bio ILIKE $${p.length} OR notes ILIKE $${p.length})`);}
 if(q.tag){p.push(q.tag);w.push(`EXISTS (SELECT 1 FROM contact_tag_links l JOIN contact_tags t ON t.id=l.tag_id AND t.workspace_id=l.workspace_id WHERE l.workspace_id=$1 AND l.contact_id=contacts.id AND t.name=$${p.length})`);}
 const rows=(await db.query(`SELECT id,full_name,email,phone,country,city,bio,company,notes,revision,created_at,updated_at FROM contacts WHERE ${w.join(' AND ')} ORDER BY created_at DESC,id DESC LIMIT 10000`,p)).rows;
 await audit(db,actor.workspace_id,actor.user_id,'contact.exported',actor.workspace_id);
 return {items:rows,count:rows.length,limited:rows.length===10000};
}
export async function setContactTags(db:PoolClient,actor:any,id:string,body:unknown){requireRole(actor.role);id=z.string().uuid().parse(id);const d=z.object({requestId:z.string().uuid(),tags:z.array(z.object({name:z.string().trim().min(1).max(80),color:z.string().regex(/^#[0-9A-Fa-f]{6}$/).nullable().optional()}).strict()).max(30)}).strict().parse(body);const payload={id,...d};if(new Set(d.tags.map(t=>t.name)).size!==d.tags.length)throw new HttpError(400,'DUPLICATE_TAG');await db.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[`knowledge:${actor.workspace_id}:${d.requestId}`]);const previous=(await db.query('SELECT operation,payload=$3::jsonb AS same,response FROM knowledge_mutations WHERE workspace_id=$1 AND request_id=$2',[actor.workspace_id,d.requestId,JSON.stringify(payload)])).rows[0];if(previous){if(previous.operation!=='contact.tags_updated'||!previous.same)throw new HttpError(409,'IDEMPOTENCY_CONFLICT');return previous.response;}const c=(await db.query('SELECT id FROM contacts WHERE workspace_id=$1 AND id=$2 AND deleted_at IS NULL FOR UPDATE',[actor.workspace_id,id])).rows[0];if(!c)throw new HttpError(404,'NOT_FOUND');await db.query('DELETE FROM contact_tag_links WHERE workspace_id=$1 AND contact_id=$2',[actor.workspace_id,id]);for(const t of [...d.tags].sort((a,b)=>a.name.localeCompare(b.name))){const tagId=uuid();const tag=(await db.query('INSERT INTO contact_tags(id,workspace_id,name,color,created_by) VALUES($1,$2,$3,$4,$5) ON CONFLICT(workspace_id,name) DO UPDATE SET color=coalesce(EXCLUDED.color,contact_tags.color) RETURNING id',[tagId,actor.workspace_id,t.name,t.color??null,actor.user_id])).rows[0];await db.query('INSERT INTO contact_tag_links(workspace_id,contact_id,tag_id) VALUES($1,$2,$3)',[actor.workspace_id,id,tag.id]);}const response=(await db.query('SELECT t.id,t.name,t.color FROM contact_tags t JOIN contact_tag_links l ON l.tag_id=t.id WHERE l.workspace_id=$1 AND l.contact_id=$2 ORDER BY t.name',[actor.workspace_id,id])).rows;await audit(db,actor.workspace_id,actor.user_id,'contact.tags_updated',id);await db.query('INSERT INTO knowledge_mutations(workspace_id,request_id,operation,payload,response) VALUES($1,$2,$3,$4::jsonb,$5::jsonb)',[actor.workspace_id,d.requestId,'contact.tags_updated',JSON.stringify(payload),JSON.stringify(response)]);return response;}
export async function listContactTags(db:PoolClient,actor:any){requireRole(actor.role,['Owner','Admin']);return (await db.query('SELECT id,name,color,created_at FROM contact_tags WHERE workspace_id=$1 ORDER BY name,id',[actor.workspace_id])).rows;}

export async function getContact(db:PoolClient,actor:any,id:string){
 requireRole(actor.role,['Owner','Admin']);id=z.string().uuid().parse(id);
 const row=(await db.query('SELECT id,full_name,email,phone,country,city,bio,company,notes,revision,created_at,updated_at FROM contacts WHERE workspace_id=$1 AND id=$2 AND deleted_at IS NULL',[actor.workspace_id,id])).rows[0];
 if(!row)throw new HttpError(404,'NOT_FOUND');const tags=(await db.query('SELECT t.id,t.name,t.color FROM contact_tag_links l JOIN contact_tags t ON t.id=l.tag_id AND t.workspace_id=l.workspace_id WHERE l.workspace_id=$1 AND l.contact_id=$2 ORDER BY t.name,t.id',[actor.workspace_id,id])).rows;return {...row,tags};
}

export async function updateContact(db:PoolClient,actor:any,id:string,body:unknown){
 requireRole(actor.role);id=z.string().uuid().parse(id);
 const d=schema.extend({expectedRevision:z.number().int().positive()}).parse(body);
 const payload={id,...d};
 await db.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[`knowledge:${actor.workspace_id}:${d.requestId}`]);
 const old=(await db.query('SELECT operation,payload=$3::jsonb AS same,response FROM knowledge_mutations WHERE workspace_id=$1 AND request_id=$2',[actor.workspace_id,d.requestId,payload])).rows[0];
 if(old){if(old.operation!=='contact.updated'||!old.same)throw new HttpError(409,'IDEMPOTENCY_CONFLICT');return old.response;}
 const current=(await db.query('SELECT revision FROM contacts WHERE workspace_id=$1 AND id=$2 AND deleted_at IS NULL FOR UPDATE',[actor.workspace_id,id])).rows[0];
 if(!current)throw new HttpError(404,'NOT_FOUND');if(current.revision!==d.expectedRevision)throw new HttpError(409,'VERSION_CONFLICT');
 await db.query('UPDATE contacts SET full_name=$3,email=$4,phone=$5,country=$6,city=$7,bio=$8,company=$9,notes=$10,revision=revision+1,updated_at=now() WHERE workspace_id=$1 AND id=$2',[actor.workspace_id,id,d.fullName,d.email??null,d.phone??null,d.country??null,d.city??null,d.bio??null,d.company??null,d.notes??null]);
 const response=await getContact(db,actor,id);
 await audit(db,actor.workspace_id,actor.user_id,'contact.updated',id);
 await db.query('INSERT INTO knowledge_mutations(workspace_id,request_id,operation,payload,response) VALUES($1,$2,$3,$4,$5)',[actor.workspace_id,d.requestId,'contact.updated',payload,response]);return response;
}

export async function deleteContact(db:PoolClient,actor:any,id:string,body:unknown){
 requireRole(actor.role);id=z.string().uuid().parse(id);const d=z.object({requestId:z.string().uuid(),expectedRevision:z.number().int().positive()}).strict().parse(body);const payload={id,...d};await db.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[`knowledge:${actor.workspace_id}:${d.requestId}`]);const old=(await db.query('SELECT operation,payload=$3::jsonb AS same,response FROM knowledge_mutations WHERE workspace_id=$1 AND request_id=$2',[actor.workspace_id,d.requestId,payload])).rows[0];if(old){if(old.operation!=='contact.deleted'||!old.same)throw new HttpError(409,'IDEMPOTENCY_CONFLICT');return old.response;}const row=(await db.query('SELECT revision FROM contacts WHERE workspace_id=$1 AND id=$2 AND deleted_at IS NULL FOR UPDATE',[actor.workspace_id,id])).rows[0];if(!row)throw new HttpError(404,'NOT_FOUND');if(row.revision!==d.expectedRevision)throw new HttpError(409,'VERSION_CONFLICT');await db.query('UPDATE contacts SET deleted_at=now(),revision=revision+1,updated_at=now() WHERE workspace_id=$1 AND id=$2',[actor.workspace_id,id]);const response={id,state:'DELETED'};await audit(db,actor.workspace_id,actor.user_id,'contact.deleted',id);await db.query('INSERT INTO knowledge_mutations(workspace_id,request_id,operation,payload,response) VALUES($1,$2,$3,$4,$5)',[actor.workspace_id,d.requestId,'contact.deleted',payload,response]);return response;
}

export async function restoreContact(db:PoolClient,actor:any,id:string,body:unknown){
 requireRole(actor.role);id=z.string().uuid().parse(id);const d=z.object({requestId:z.string().uuid(),expectedRevision:z.number().int().positive()}).strict().parse(body);const payload={id,...d};await db.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[`knowledge:${actor.workspace_id}:${d.requestId}`]);const old=(await db.query('SELECT operation,payload=$3::jsonb AS same,response FROM knowledge_mutations WHERE workspace_id=$1 AND request_id=$2',[actor.workspace_id,d.requestId,payload])).rows[0];if(old){if(old.operation!=='contact.restored'||!old.same)throw new HttpError(409,'IDEMPOTENCY_CONFLICT');return old.response;}const row=(await db.query('SELECT revision FROM contacts WHERE workspace_id=$1 AND id=$2 AND deleted_at IS NOT NULL FOR UPDATE',[actor.workspace_id,id])).rows[0];if(!row)throw new HttpError(404,'NOT_FOUND');if(row.revision!==d.expectedRevision)throw new HttpError(409,'VERSION_CONFLICT');await db.query('UPDATE contacts SET deleted_at=NULL,revision=revision+1,updated_at=now() WHERE workspace_id=$1 AND id=$2',[actor.workspace_id,id]);const response=await getContact(db,actor,id);await audit(db,actor.workspace_id,actor.user_id,'contact.restored',id);await db.query('INSERT INTO knowledge_mutations(workspace_id,request_id,operation,payload,response) VALUES($1,$2,$3,$4,$5)',[actor.workspace_id,d.requestId,'contact.restored',payload,response]);return response;
}

export async function mergeContacts(db:PoolClient,actor:any,body:unknown){
 requireRole(actor.role);const d=z.object({requestId:z.string().uuid(),primaryId:z.string().uuid(),secondaryId:z.string().uuid(),primaryRevision:z.number().int().positive(),secondaryRevision:z.number().int().positive()}).strict().parse(body);if(d.primaryId===d.secondaryId)throw new HttpError(400,'SAME_CONTACT');const payload=d;await db.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[`knowledge:${actor.workspace_id}:${d.requestId}`]);const old=(await db.query('SELECT operation,payload=$3::jsonb AS same,response FROM knowledge_mutations WHERE workspace_id=$1 AND request_id=$2',[actor.workspace_id,d.requestId,payload])).rows[0];if(old){if(old.operation!=='contact.merged'||!old.same)throw new HttpError(409,'IDEMPOTENCY_CONFLICT');return old.response;}const ids=[d.primaryId,d.secondaryId].sort();const rows=(await db.query('SELECT id,full_name,email,phone,country,city,bio,company,notes,revision FROM contacts WHERE workspace_id=$1 AND id=ANY($2::uuid[]) AND deleted_at IS NULL ORDER BY id FOR UPDATE',[actor.workspace_id,ids])).rows;if(rows.length!==2)throw new HttpError(404,'NOT_FOUND');const primary=rows.find((r:any)=>r.id===d.primaryId),secondary=rows.find((r:any)=>r.id===d.secondaryId);if(primary.revision!==d.primaryRevision||secondary.revision!==d.secondaryRevision)throw new HttpError(409,'VERSION_CONFLICT');const v=(k:string)=>primary[k]??secondary[k]??null;await db.query('UPDATE contacts SET email=$3,phone=$4,country=$5,city=$6,bio=$7,company=$8,notes=$9,revision=revision+1,updated_at=now() WHERE workspace_id=$1 AND id=$2',[actor.workspace_id,d.primaryId,v('email'),v('phone'),v('country'),v('city'),v('bio'),v('company'),v('notes')]);await db.query('UPDATE contacts SET deleted_at=now(),revision=revision+1,updated_at=now() WHERE workspace_id=$1 AND id=$2',[actor.workspace_id,d.secondaryId]);await db.query('INSERT INTO contact_merge_history(id,workspace_id,request_id,primary_id,secondary_id,primary_before,secondary_before) VALUES($1,$2,$3,$4,$5,$6,$7)',[uuid(),actor.workspace_id,d.requestId,d.primaryId,d.secondaryId,primary,secondary]);const response={primaryId:d.primaryId,mergedId:d.secondaryId,state:'MERGED',contact:{...primary,email:v('email'),phone:v('phone'),country:v('country'),city:v('city'),bio:v('bio'),company:v('company'),notes:v('notes'),revision:primary.revision+1}};await audit(db,actor.workspace_id,actor.user_id,'contact.merged',d.primaryId);await audit(db,actor.workspace_id,actor.user_id,'contact.deleted',d.secondaryId);await db.query('INSERT INTO knowledge_mutations(workspace_id,request_id,operation,payload,response) VALUES($1,$2,$3,$4,$5)',[actor.workspace_id,d.requestId,'contact.merged',payload,response]);return response;
}

export async function previewMergeContacts(db:PoolClient,actor:any,query:unknown){
 requireRole(actor.role);const q=z.object({primaryId:z.string().uuid(),secondaryId:z.string().uuid()}).strict().parse(query);if(q.primaryId===q.secondaryId)throw new HttpError(400,'SAME_CONTACT');const rows=(await db.query('SELECT id,full_name,email,phone,country,city,bio,company,notes,revision FROM contacts WHERE workspace_id=$1 AND id=ANY($2::uuid[]) AND deleted_at IS NULL ORDER BY id',[actor.workspace_id,[q.primaryId,q.secondaryId]])).rows;if(rows.length!==2)throw new HttpError(404,'NOT_FOUND');const primary=rows.find((r:any)=>r.id===q.primaryId),secondary=rows.find((r:any)=>r.id===q.secondaryId);const fields=['full_name','email','phone','country','city','bio','company','notes'];const result:any={};for(const key of fields)result[key]={primary:primary[key],secondary:secondary[key],selected:primary[key]??secondary[key]??null,source:primary[key]!=null?'primary':secondary[key]!=null?'secondary':'empty'};return {primaryId:q.primaryId,secondaryId:q.secondaryId,primaryRevision:primary.revision,secondaryRevision:secondary.revision,fields:result};
}

export async function undoMergeContacts(db:PoolClient,actor:any,body:unknown){
 requireRole(actor.role);const d=z.object({requestId:z.string().uuid(),mergeRequestId:z.string().uuid()}).strict().parse(body);await db.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[`knowledge:${actor.workspace_id}:${d.requestId}`]);const old=(await db.query('SELECT operation,payload=$3::jsonb AS same,response FROM knowledge_mutations WHERE workspace_id=$1 AND request_id=$2',[actor.workspace_id,d.requestId,d])).rows[0];if(old){if(old.operation!=='contact.merge_undone'||!old.same)throw new HttpError(409,'IDEMPOTENCY_CONFLICT');return old.response;}const h=(await db.query('SELECT * FROM contact_merge_history WHERE workspace_id=$1 AND request_id=$2 AND undone_at IS NULL FOR UPDATE',[actor.workspace_id,d.mergeRequestId])).rows[0];if(!h)throw new HttpError(404,'NOT_FOUND');const p=h.primary_before,s=h.secondary_before;const current=(await db.query('SELECT id,revision,deleted_at FROM contacts WHERE workspace_id=$1 AND id=ANY($2::uuid[]) ORDER BY id FOR UPDATE',[actor.workspace_id,[h.primary_id,h.secondary_id]])).rows;const primary=current.find(r=>r.id===h.primary_id),secondary=current.find(r=>r.id===h.secondary_id);if(!primary||!secondary||primary.revision!==p.revision+1||secondary.revision!==s.revision+1||primary.deleted_at!==null||secondary.deleted_at===null)throw new HttpError(409,'VERSION_CONFLICT');await db.query('UPDATE contacts SET email=$3,phone=$4,country=$5,city=$6,bio=$7,company=$8,notes=$9,deleted_at=NULL,revision=revision+1,updated_at=now() WHERE workspace_id=$1 AND id=$2',[actor.workspace_id,h.primary_id,p.email,p.phone,p.country,p.city,p.bio,p.company,p.notes]);await db.query('UPDATE contacts SET full_name=$3,email=$4,phone=$5,country=$6,city=$7,bio=$8,company=$9,notes=$10,deleted_at=NULL,revision=revision+1,updated_at=now() WHERE workspace_id=$1 AND id=$2',[actor.workspace_id,h.secondary_id,s.full_name,s.email,s.phone,s.country,s.city,s.bio,s.company,s.notes]);await db.query('UPDATE contact_merge_history SET undone_at=now() WHERE id=$1',[h.id]);const response={primaryId:h.primary_id,restoredId:h.secondary_id,state:'MERGE_UNDONE'};await audit(db,actor.workspace_id,actor.user_id,'contact.merge_undone',h.primary_id);await db.query('INSERT INTO knowledge_mutations(workspace_id,request_id,operation,payload,response) VALUES($1,$2,$3,$4,$5)',[actor.workspace_id,d.requestId,'contact.merge_undone',d,response]);return response;
}
